# -*- coding: utf-8 -*-
"""admg2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EqjC34A9edHXSV2hyG-IpB22e4ecj9_O
"""

#!git clone https://gitlab.com/rbhatta8/dcd.git

#%cd dcd

#!git clone https://gitlab.com/causal/ananke.git

import numpy as np
import autograd.numpy as anp
from autograd import grad
from autograd.extend import primitive, defvjp
import functools
import scipy.optimize as sopt
import pandas as pd
# from ananke.graphs import ADMG
from scipy.special import comb
import copy
#from ricf import bic
#!pip install causal-learn
#!pip install python-igraph
import igraph as ig
from causallearn.graph.Dag import Dag
from causallearn.graph.GraphNode import GraphNode
from causallearn.utils.DAG2PAG import dag2pag
from causallearn.graph.Endpoint import Endpoint

# ============================================================
# Ground-truth generation by ER graphs
# ============================================================

def _graph_to_adjmat(G):
    return np.array(G.get_adjacency().data, dtype=np.float64)

def simulate_er_dag_igraph(d: int, p_edge: float, rng=None):
    """
    用 igraph 生成 ER 无向图，再随机赋予一个拓扑顺序，定向成 DAG。
    约定: S[i,j]=1 表示 i -> j
    """
    if rng is None:
        rng = np.random.default_rng()

    p_edge = float(np.clip(p_edge, 0.0, 1.0))
    G_und = ig.Graph.Erdos_Renyi(n=d, p=p_edge, directed=False, loops=False)
    A_und = _graph_to_adjmat(G_und)

    perm = rng.permutation(d)
    pos = np.empty(d, dtype=int)
    pos[perm] = np.arange(d)

    S = np.zeros((d, d), dtype=np.float64)
    for i in range(d):
        for j in range(i + 1, d):
            if A_und[i, j] != 0:
                if pos[i] < pos[j]:
                    S[i, j] = 1.0
                else:
                    S[j, i] = 1.0
    return S

def simulate_er_bidirected_igraph(d: int, p_edge: float, rng=None):
    """
    用 igraph 生成无向 ER 图作为 bidirected 结构。
    返回对称 0/1 矩阵 C，且对角线为 1。
    """
    if rng is None:
        rng = np.random.default_rng()

    p_edge = float(np.clip(p_edge, 0.0, 1.0))
    G = ig.Graph.Erdos_Renyi(n=d, p=p_edge, directed=False, loops=False)
    A = _graph_to_adjmat(G)

    C = ((A + A.T) > 0).astype(np.float64)
    np.fill_diagonal(C, 1.0)
    return C

def sample_weighted_B_from_S(
    S,
    rng=None,
    abs_low=0.3,
    abs_high=1.5,
    allow_negative=True,
):
    """
    根据 0/1 结构矩阵 S 生成 weighted B_true.
    约定: B[i,j] 表示 i -> j
    """
    if rng is None:
        rng = np.random.default_rng()

    d = S.shape[0]
    B = np.zeros((d, d), dtype=np.float64)

    rows, cols = np.where(S != 0)
    for i, j in zip(rows, cols):
        mag = rng.uniform(abs_low, abs_high)
        sign = rng.choice([-1.0, 1.0]) if allow_negative else 1.0
        B[i, j] = sign * mag

    return B

def sample_weighted_Omega_from_C(
    C,
    rng=None,
    diag_low=1.0,
    diag_high=2.0,
    off_abs_low=0.1,
    off_abs_high=0.6,
    allow_negative=True,
    spd_floor=1e-3,
):
    """
    根据 0/1 结构矩阵 C 生成 weighted Omega_true.
    - 对角线随机正值
    - C[i,j]=1 的非对角位置给随机权重
    - 最后通过最小特征值修正保证正定:
          Omega <- Omega + soft_shift * I
      这里直接用线性 shift:
          shift = max(0, spd_floor - lambda_min)
    """
    if rng is None:
        rng = np.random.default_rng()

    d = C.shape[0]
    Omega = np.zeros((d, d), dtype=np.float64)

    diag_vals = rng.uniform(diag_low, diag_high, size=d)
    np.fill_diagonal(Omega, diag_vals)

    for i in range(d):
        for j in range(i + 1, d):
            if C[i, j] != 0:
                mag = rng.uniform(off_abs_low, off_abs_high)
                sign = rng.choice([-1.0, 1.0]) if allow_negative else 1.0
                val = sign * mag
                Omega[i, j] = val
                Omega[j, i] = val

    eigvals = np.linalg.eigvalsh(Omega)
    lam_min = eigvals.min()
    shift = max(0.0, spd_floor - lam_min)
    if shift > 0:
        Omega = Omega + shift * np.eye(d, dtype=np.float64)

    return Omega

def generate_random_ground_truth_er(
    d,
    p_dir,
    p_bidir,
    seed=None,
    B_abs_low=0.3,
    B_abs_high=1.5,
    Omega_diag_low=1.0,
    Omega_diag_high=2.0,
    Omega_off_abs_low=0.1,
    Omega_off_abs_high=0.6,
    B_allow_negative=True,
    Omega_allow_negative=True,
    spd_floor=1e-3,
):
    """
    一次性生成:
      - S_true: ER DAG 结构
      - C_true: ER bidirected 结构
      - B_true: 根据 S_true 加权
      - Omega_true: 根据 C_true 加权并修正为 SPD
    """
    rng = np.random.default_rng(seed)

    S_true = simulate_er_dag_igraph(d=d, p_edge=p_dir, rng=rng)
    C_true = simulate_er_bidirected_igraph(d=d, p_edge=p_bidir, rng=rng)

    B_true = sample_weighted_B_from_S(
        S_true,
        rng=rng,
        abs_low=B_abs_low,
        abs_high=B_abs_high,
        allow_negative=B_allow_negative,
    )

    Omega_true = sample_weighted_Omega_from_C(
        C_true,
        rng=rng,
        diag_low=Omega_diag_low,
        diag_high=Omega_diag_high,
        off_abs_low=Omega_off_abs_low,
        off_abs_high=Omega_off_abs_high,
        allow_negative=Omega_allow_negative,
        spd_floor=spd_floor,
    )

    return {
        "d": d,
        "S_true": S_true,
        "C_true": C_true,
        "B_true": B_true,
        "Omega_true": Omega_true,
    }


# ============================================================
# 0. Fixed convention
# ============================================================
# S[i,j] = 1 means i -> j
# B[i,j] != 0 means i -> j
# fixed topological order: only i < j directed edges are allowed


# ============================================================
# 2. Data simulation
# ============================================================

def simulate_linear_scm_i_to_j(n, B, Omega, seed=42):
    """
    X = E (I - B)^(-1), where B[i,j] means i -> j.
    """
    rng = np.random.default_rng(seed)
    p = B.shape[0]
    L = np.linalg.cholesky(Omega)
    E = rng.standard_normal((n, p)) @ L.T
    X = E @ np.linalg.inv(np.eye(p) - B)
    return X


# ============================================================
# 3. SHD
# ============================================================

def admg_to_pag(p, edges=None, biedges=None, B_mat=None, Sigma_mat=None):
    """
    将 ADMG 转换为 PAG
    参数:
    - p: 观测变量的数量 (int)
    - edges: 有向边列表, 如 [(0, 2)]
    - biedges: 双向边列表, 如 [(0, 1), (1, 2)]
    - B_mat: 有向边权重矩阵 (可选)
    - Sigma_mat: 噪声协方差矩阵 (可选)
    """

    # 1. 初始化观测变量节点
    nodes = [GraphNode(str(i)) for i in range(p)]
    all_nodes = list(nodes)
    latent_nodes = []

    # 2. 创建一个空的 DAG 对象
    # 注意：dag2pag 需要输入一个包含显变量和隐变量的完整 DAG
    dag = Dag(all_nodes)

    # 3. 处理有向边 (Directed Edges)
    if B_mat is not None:
        # 从矩阵提取有向边 (B_ij 表示 i -> j)
        for i in range(p):
            for j in range(p):
                if B_mat[i, j] != 0:
                    dag.add_directed_edge(nodes[i], nodes[j])
    elif edges is not None:
        for i, j in edges:
            dag.add_directed_edge(nodes[i], nodes[j])

    # 4. 处理双向边 (Bidirected Edges) -> 转换为隐变量结构
    # 每条双向边 i <-> j 变成 L -> i 和 L -> j
    if Sigma_mat is not None:
        # 从矩阵提取双向边 (只看上三角，排除对角线)
        for i in range(p):
            for j in range(i + 1, p):
                if Sigma_mat[i, j] != 0:
                    # 创建新的隐变量节点
                    l_node = GraphNode(f"L_{i}_{j}")
                    dag.add_node(l_node)
                    latent_nodes.append(l_node)
                    # 添加从隐变量到两个观测点的有向边
                    dag.add_directed_edge(l_node, nodes[i])
                    dag.add_directed_edge(l_node, nodes[j])
    elif biedges is not None:
        for i, j in biedges:
            l_node = GraphNode(f"L_{i}_{j}")
            dag.add_node(l_node)
            latent_nodes.append(l_node)
            dag.add_directed_edge(l_node, nodes[i])
            dag.add_directed_edge(l_node, nodes[j])

    # 5. 调用 causal-learn 函数将 DAG 转为 PAG
    # 第二个参数是需要 marginalize 掉的隐变量列表
    pag = dag2pag(dag, latent_nodes)

    return pag

def compute_pag_metrics(true_pag, est_pag):
    """
    计算 SHD, Skeleton F1, Arrowhead F1
    基于 causal-learn 的 GeneralGraph 对象
    """
    # 获取邻接矩阵 (graph property stores the matrix)
    # causal-learn 矩阵定义: M[i, j] 表示 i 和 j 之间在 j 端点的类型
    # 0: No Edge, 1: Circle, 2: Arrow, 3: Tail

    true_adj = true_pag.graph
    est_adj = est_pag.graph
    p = true_adj.shape[0]

    # --- 1. Skeleton F1 ---
    # 只需要看是否有边 (非0)，只遍历上三角避免重复
    tp_skel = 0
    fp_skel = 0
    fn_skel = 0

    for i in range(p):
        for j in range(i + 1, p):
            has_edge_true = (true_adj[i, j] != 0)
            has_edge_est = (est_adj[i, j] != 0)

            if has_edge_true and has_edge_est:
                tp_skel += 1
            elif not has_edge_true and has_edge_est:
                fp_skel += 1
            elif has_edge_true and not has_edge_est:
                fn_skel += 1

    precision_skel = tp_skel / (tp_skel + fp_skel) if (tp_skel + fp_skel) > 0 else 0
    recall_skel = tp_skel / (tp_skel + fn_skel) if (tp_skel + fn_skel) > 0 else 0
    f1_skel = 2 * precision_skel * recall_skel / (precision_skel + recall_skel) if (precision_skel + recall_skel) > 0 else 0

    # --- 2. Arrowhead F1 ---
    # 统计所有箭头 (Arrow = 2) 的预测情况
    # 遍历整个矩阵 (包括 i,j 和 j,i)，因为箭头是有方向的
    tp_arrow = 0
    fp_arrow = 0
    fn_arrow = 0

    # ARROW 在 causal-learn Endpoint 中通常对应值 2
    ARROW_MARK = Endpoint.ARROW.value

    for i in range(p):
        for j in range(p):
            if i == j: continue

            # True PAG 在 j 处是否有箭头
            is_arrow_true = (true_adj[i, j] == ARROW_MARK)
            # Est PAG 在 j 处是否有箭头
            is_arrow_est = (est_adj[i, j] == ARROW_MARK)

            if is_arrow_true and is_arrow_est:
                tp_arrow += 1
            elif not is_arrow_true and is_arrow_est:
                fp_arrow += 1
            elif is_arrow_true and not is_arrow_est:
                fn_arrow += 1

    precision_arrow = tp_arrow / (tp_arrow + fp_arrow) if (tp_arrow + fp_arrow) > 0 else 0
    recall_arrow = tp_arrow / (tp_arrow + fn_arrow) if (tp_arrow + fn_arrow) > 0 else 0
    f1_arrow = 2 * precision_arrow * recall_arrow / (precision_arrow + recall_arrow) if (precision_arrow + recall_arrow) > 0 else 0

    # --- 3. SHD (Structural Hamming Distance) ---
    # 定义：增加/删除边 + 修改端点方向的操作总数
    # 策略：
    # - 边存在性不同: SHD + 1.5
    # - 边存在且相同: 检查两个端点，每个端点不同 SHD + 0.5 (累计为1)

    shd = 0
    for i in range(p):
        for j in range(i + 1, p):
            diff = (true_adj[i,j]!=est_adj[i,j])or(true_adj[j,i]!=est_adj[j,i])
            if diff: shd+=1.0

    return {
        "shd": int(shd) if shd.is_integer() else shd,
        "f1_skeleton": round(f1_skel, 4),
        "f1_arrowhead": round(f1_arrow, 4),
        "precision_arrow": round(precision_arrow, 4),
        "recall_arrow": round(recall_arrow, 4)
    }

@primitive
def cycle_loss(W):
    """
    Compute the loss due to directed cycles in the induced graph of W.

    :param W: numpy matrix.
    :return: float corresponding to penalty on directed cycles.
    """
    d = len(W)
    M = np.eye(d) + W * W/d
    E = np.linalg.matrix_power(M, d - 1)
    return (E.T * M).sum() - d


# ∇h(W) = [exp(W ◦ W)]^T ◦ 2W
def dcycle_loss(ans, W):
    """
    Analytic derivatives for the cycle loss function.

    :param ans:
    :param W: numpy matrix.
    :return: gradients for the cycle loss.
    """
    W_shape = W.shape
    d = len(W)
    M = anp.eye(d) + W*W/d
    E = anp.linalg.matrix_power(M, d-1)
    return lambda g: anp.full(W_shape, g) * E.T * W * 2


# required for autograd
defvjp(cycle_loss, dcycle_loss)

def ancestrality_loss(W1, W2):
    """
    Compute the loss due to violations of ancestrality in the induced ADMG of W1, W2.

    :param W1: numpy matrix for directed edge coefficients.
    :param W2: numpy matrix for bidirected edge coefficients.
    :return: float corresponding to penalty on violations of ancestrality.
    """
    d = len(W1)
    W1_pos = anp.multiply(W1, W1)
    W2_pos = anp.multiply(W2, W2)
    W1k = np.eye(d)
    M = np.eye(d)
    for k in range(1, d):
        W1k = anp.dot(W1k, W1_pos)
        # M += comb(d, k) * (1 ** k) * W1k
        M += 1.0/np.math.factorial(k) * W1k

    return anp.sum(anp.multiply(M, W2_pos))

def bow_loss(W1, W2):
    """
    Compute the loss due to presence of bows in the induced ADMG of W1, W2.

    :param W1: numpy matrix for directed edge coefficients.
    :param W2: numpy matrix for bidirected edge coefficients.
    :return: float corresponding to penalty on bows.
    """
    W1_pos = anp.multiply(W1, W1)/len(W1)
    W2_pos = anp.multiply(W2, W2)/len(W1)
    return anp.sum(anp.multiply(W1_pos, W2_pos))

def reachable_loss(W1, W2, alpha_d=1, alpha_b=2, s=anp.log(5000)):
    """
    Compute the loss due to presence of c-trees in the induced ADMG of W1, W2.

    :param W1: numpy matrix for directed edge coefficients.
    :param W2: numpy matrix for bidirected edge coefficients.
    :return: float corresponding to penalty on c-trees.
    """

    d = len(W1)
    greenery = 0

    # iterate over each vertex in turn
    for var_index in range(d):

        # create a for Vi and an inverse mask
        mask = anp.array([1 if i == var_index else 0 for i in range(d)]) * 1
        W1_fixed = anp.multiply(W1, W1)
        W2_fixed = anp.multiply(W2, W2)

        # try to "primal fix" at most d-1 times
        for i in range(d-1):

            # compute binomial expansion of sum((I + \alpha B)^k \circ D))
            Bk = np.eye(d)
            M = np.eye(d)
            for k in range(1, d):
                Bk = anp.dot(Bk, W2_fixed)
                M += comb(d, k) * (alpha_b ** k) * Bk

            # compute the primal fixability mask
            p_fixability_matrix = anp.multiply(M, W1_fixed)
            e2x = anp.exp(anp.clip(s*(anp.mean(p_fixability_matrix, axis=1) + mask), 0, 4))
            fixability = (e2x - 1)/(e2x + 1)
            fixability_mask = anp.vstack([fixability for _ in range(d)])

            # apply the primal fixing operation
            W1_fixed = anp.multiply(W1_fixed, fixability_mask)
            W2_fixed = anp.multiply(W2_fixed, fixability_mask)
            W2_fixed = anp.multiply(W2_fixed, fixability_mask.T)

        # compute (I + \alpha A)^k for A = W1_fixed and W2_fixed
        Bk, Dk = np.eye(d), np.eye(d)
        eW1_fixed, eW2_fixed = np.eye(d), np.eye(d)

        for k in range(1, d):
            Dk = anp.dot(Dk, W1_fixed)
            Bk = anp.dot(Bk, W2_fixed)
            #eW1_fixed += 1/np.math.factorial(k) * Dk
            #eW2_fixed += 1/np.math.factorial(k) * Bk
            eW1_fixed += comb(d, k) * (alpha_d ** k) * Dk
            eW2_fixed += comb(d, k) * (alpha_b ** k) * Bk

        # compute penalty on Vi-rooted c-tree
        greenery += anp.sum(anp.multiply(eW1_fixed[:, var_index], eW2_fixed[:, var_index])) - 1

    return greenery

import numpy as np
import autograd.numpy as anp
from autograd import grad
from autograd.extend import primitive, defvjp
import functools
import scipy.optimize as sopt
import pandas as pd
# from ananke.graphs import ADMG # This library is not available, so I'm replacing it with a custom class
from scipy.special import comb
import copy
# from ricf import bic # This library is not available, commenting it out for now

# Custom class to replace ananke.graphs.ADMG
class SimpleADMG:
    """
    A simple class to represent an ADMG for testing purposes.
    """
    def __init__(self, vertices):
        self.vertices = vertices
        self.di_edges = set()
        self.bi_edges = set()

    def add_diedge(self, u, v):
        self.di_edges.add((u, v))

    def add_biedge(self, u, v):
        # Bidirected edges are undirected, so we store them sorted
        self.bi_edges.add(tuple(sorted((u, v))))

    def has_biedge(self, u, v):
        return tuple(sorted((u, v))) in self.bi_edges


class Discovery:
    """
    Class for structure learning/causal discovery in ADMGs
    """

    def __init__(self, lamda=0.05):
        """
        Constructor.

        :param lamda: float > 0 corresponding to L0-regularization strength.
        """

        self.X_ = None
        self.S_ = None
        self.Z_ = None
        self.W1_ = None
        self.W2_ = None
        self.Wii_ = None
        self.convergence_ = None
        self.lamda = lamda
        self.G_ = None

    def primal_loss(self, params, rho, alpha, Z, structure_penalty_func):
        """
        Calculate the primal loss.

        :param params: parameter vector theta that can be reshaped into directed/bidirected coefs.
        :param rho: penalty on loss due to violations of given ADMG class.
        :param alpha: dual ascent Lagrangian parameter.
        :param Z: dictionary mapping Vi to pseudovariables computed for Vi.
        :param structure_penalty_func: function computing loss for ancestrality, aridity, bow-freenes.
        :return: float corresponding to the loss.
        """

        n, d = self.X_.shape
        W1 = anp.reshape(params[0:d * d], (d, d))
        W2 = anp.reshape(params[d * d:], (d, d))
        W2 = W2 + W2.T

        loss = 0.0
        for var_index in range(d):
            loss += 0.5 / n * anp.linalg.norm(self.X_[:, var_index] - anp.dot(self.X_, W1[:, var_index]) -
                                                            anp.dot(Z[var_index], W2[:, var_index])) ** 2

        structure_penalty = cycle_loss(W1) + structure_penalty_func(W1, W2)
        structure_penalty = 0.5 * rho * (structure_penalty ** 2) + alpha * structure_penalty
        eax2 = anp.exp((anp.log(n) * anp.abs(params)))
        tanh = (eax2 - 1) / (eax2 + 1)
        return loss + structure_penalty + anp.sum(tanh) * self.lamda

    def _create_bounds(self, tiers, unconfounded_vars, var_names):
        """
        Create bounds on parameters given prior knowledge.

        :param tiers: iterable over iterables corresponding to variable tiers.
        :param unconfounded_vars: iterable of names of variables that have no incoming bidirected edges.
        :param var_names: names of all variables in the problem.
        :return: iterable of tuples corresponding to bounds on possible values of the parameters.
        """

        if tiers is None:
            tiers = [var_names]

        unconfounded_vars = set(unconfounded_vars)

        # dictionary containing what tier each variable is in
        tier_dict = {}
        for tier_num in range(len(tiers)):
            for var in tiers[tier_num]:
                tier_dict[var] = tier_num

        # set bounds on possible values by applying background knowledge
        bounds_directed_edges = []
        bounds_bidirected_edges = []
        for i in range(len(var_names)):
            for j in range(len(var_names)):

                # no self loops
                if i == j:
                    bounds_directed_edges.append((0, 0))

                # i -> j is not allowed if i appears later in the causal order
                elif tier_dict[var_names[i]] > tier_dict[var_names[j]]:
                    bounds_directed_edges.append((0, 0))

                # otherwise i -> j is allowed
                else:
                    bounds_directed_edges.append((-4, 4))

                # no self confounding and enforce symmetry
                if i <= j:
                    bounds_bidirected_edges.append((0, 0))

                # no confounding between i and j if either are unconfounded
                elif var_names[i] in unconfounded_vars or var_names[j] in unconfounded_vars:
                    bounds_bidirected_edges.append((0, 0))

                # otherwise i <-> j is allowed
                else:
                    bounds_bidirected_edges.append((-4, 4))
        return bounds_directed_edges + bounds_bidirected_edges

    def _compute_pseudo_variables(self, W1, W2):
        """
        Compute pseudo-variables for a given set of parameters for directed and bidirected edges.

        :param W1: coefficients for directed edges.
        :param W2: covariance matrix for residual noise terms (bidirected edge coefficients).
        :return: dictionary mapping Vi to its pseudovariables.
        """

        # iterate over each vertex and get Zi
        Z = {}
        d = len(W1)
        for var_index in range(d):

            # get omega_{-i, -i}
            indices = list(range(0, var_index)) + list(range(var_index + 1, d))
            omega_minusii = W2[anp.ix_(indices, indices)]
            omega_minusii_inv = anp.linalg.inv(omega_minusii)

            # get epsilon_minusi
            # residual, ignoring the var_index column
            epsilon = self.X_ - anp.matmul(self.X_, W1)
            epsilon_minusi = anp.delete(epsilon, var_index, axis=1)

            # calculate Z_minusi
            Z_minusi = (omega_minusii_inv @ epsilon_minusi.T).T

            # insert a column of zeros to maintain the shape
            Z[var_index] = anp.insert(Z_minusi, var_index, 0, axis=1)

        return Z

    def get_graph(self, W1, W2, vertices, threshold):
        """
        Get the induced ADMG on the matrices W1 and W2.

        :param W1: directed edge coefficients.
        :param W2: bidirected edge coefficients.
        :param vertices: names of vertices in the problem.
        :param threshold: float deciding what is close enough to zero to rule out an edge.
        :return: A simple ADMG representation.
        """

        G = SimpleADMG(vertices)
        for i in range(len(vertices)):
            for j in range(len(vertices)):
                if abs(W1[i, j]) > threshold:
                    G.add_diedge(vertices[i], vertices[j])
                if i != j and abs(W2[i, j]) > threshold and not G.has_biedge(vertices[i], vertices[j]):
                    G.add_biedge(vertices[i], vertices[j])
        return G

    def _discover_admg(self, data, admg_class, tiers=None, unconfounded_vars=[], max_iter=100,
                       h_tol=1e-8, rho_max=1e+16, w_threshold=0.05,
                       ricf_increment=1, ricf_tol=1e-4, verbose=False):
        """
        Internal function for running the structure learning procedure once.

        :param data: Pandas dataframe containing data.
        :param admg_class: class of ADMGs to consider. options: ancestral, arid, or bowfree.
        :param tiers: iterable over iterables corresponding to variable tiers.
        :param unconfounded_vars: iterable of names of variables that have no incoming bidirected edges.
        :param max_iter: maximum iterations to run the dual ascent procedure.
        :param h_tol: tolerance for violations of the property defining admg_class.
        :param rho_max: maximum penalty applied to violations of the property defining admg_class.
        :param w_threshold: float deciding what is close enough to zero to rule out an edge.
        :param ricf_increment: positive integer to increase maximum number of RICF iterations at every dual ascent step.
        :param ricf_tol: tolerance for terminating RICF.
        :param verbose: Boolean indicating whether to print intermediate outputs.
        :return: best fitting Ananke ADMG that is found.
        """

        # get shape of the data, make a copy and calculate sample covariance
        self.X_ = anp.copy(data.values)
        n, d = self.X_.shape
        self.S_ = anp.cov(self.X_.T)

        # create bounds by applying background knowledge
        bounds = self._create_bounds(tiers, unconfounded_vars, data.columns)

        # initialize starting point
        W1_hat = anp.random.uniform(-0.5, 0.5, (d, d))
        W2_hat = anp.random.uniform(-0.05, 0.05, (d, d))
        W2_hat[np.tril_indices(d)] = 0
        W2_hat = W2_hat + W2_hat.T
        W2_hat = anp.multiply(W2_hat, 1 - np.eye(d))
        Wii_hat = anp.diag(anp.diag(self.S_))  # zero matrix, with only the diagonal filled

        # initial settings
        rho, alpha, h = 1.0, 0.0, np.inf
        ricf_max_iters = 1
        convergence = False

        # set loss functions according to desired ADMG class
        if admg_class == "ancestral":
            penalty = ancestrality_loss
        elif admg_class == "arid":
            penalty = reachable_loss
        elif admg_class == "bowfree":
            penalty = bow_loss
        elif admg_class == "none":
            penalty = lambda W1, W2: 0
        else:
            raise NotImplemented("Invalid ADMG class")

        # gradient stuff
        objective = functools.partial(self.primal_loss)
        gradient = grad(objective)

        # iterate till convergence or max iterations
        for num_iter in range(max_iter):

            # initialize W1, W2, Wii
            W1_new, W2_new, Wii_new = None, None, None
            h_new = None  # also keep track of loss

            while rho < rho_max:

                # initialize with the last best guess we have of these matrices
                W1_new, W2_new, Wii_new = W1_hat.copy(), W2_hat.copy(), Wii_hat.copy()

                # perform RICF till convergence or max iterations
                ricf_iter = 0
                while ricf_iter < ricf_max_iters:

                    ricf_iter += 1
                    W1_old = W1_new.copy()  # Directed edges = Beta
                    W2_old = W2_new.copy()  # Bidirected edges = Omega
                    Wii_old = Wii_new.copy()

                    # get pseudovariables
                    Z = self._compute_pseudo_variables(W1_new, W2_new + Wii_new)

                    # get values of the current estimates and solve
                    current_estimates = np.concatenate((W1_new.flatten(), W2_new.flatten()))
                    sol = sopt.minimize(self.primal_loss, current_estimates,
                                        args=(rho, alpha, Z, penalty),
                                        method='L-BFGS-B',
                                        options={'disp': False}, bounds=bounds, jac=gradient)

                    W1_new = np.reshape(sol.x[0:d * d], (d, d))
                    W2_new = np.reshape(sol.x[d * d:], (d, d))
                    W2_new = W2_new + W2_new.T

                    for var_index in range(d):
                        Wii_new[var_index, var_index] = np.var(
                            self.X_[:, var_index] - np.dot(self.X_, W1_new[:, var_index]))

                    if np.sum(np.abs(W1_old - W1_new)) + np.sum(np.abs((W2_old + Wii_old) - (W2_new + Wii_new))) < ricf_tol:
                        convergence = True
                        break

                h_new = cycle_loss(W1_new) + penalty(W1_new, W2_new)
                if verbose:
                    print(num_iter, h_new)
                    print("W1_est\n", np.round(W1_new, 3), "\n\nW2_est\n", np.round(W2_new, 3))

                if h_new < 0.25 * h:
                    break
                else:
                    rho *= 10

            W1_hat, W2_hat, Wii_hat = W1_new.copy(), W2_new.copy(), Wii_new.copy()
            h = h_new
            alpha += rho * h
            ricf_max_iters += ricf_increment
            if h <= h_tol or rho >= rho_max:
                break

        final_W1, final_W2 = W1_hat.copy(), W2_hat + Wii_hat
        final_W1[np.abs(final_W1) < w_threshold] = 0
        final_W2[np.abs(final_W2) < w_threshold] = 0
        return self.get_graph(final_W1, final_W2, data.columns, w_threshold), convergence

    def discover_admg(self, data, admg_class, tiers=None, unconfounded_vars=[], max_iter=100,
                      h_tol=1e-8, rho_max=1e+16, num_restarts=2, w_threshold=0.05,
                      ricf_increment=1, ricf_tol=1e-4, verbose=False, detailed_output=False):
        """
        Function for running the structure learning procedure within a pre-specified ADMG hypothesis class.

        :param data: Pandas dataframe containing data.
        :param admg_class: class of ADMGs to consider. options: ancestral, arid, or bowfree.
        :param tiers: iterable over iterables corresponding to variable tiers.
        :param unconfounded_vars: iterable of names of variables that have no incoming bidirected edges.
        :param max_iter: maximum iterations to run the dual ascent procedure.
        :param h_tol: tolerance for violations of the property defining admg_class.
        :param rho_max: maximum penalty applied to violations of the property defining admg_class.
        :param w_threshold: float deciding what is close enough to zero to rule out an edge.
        :param ricf_increment: positive integer to increase maximum number of RICF iterations at every dual ascent step.
        :param ricf_tol: tolerance for terminating RICF.
        :param verbose: Boolean indicating whether to print intermediate outputs.
        :param detailed_output: Boolean indicating whether to print detailed intermediate outputs.
        :return: best fitting Ananke ADMG that is found.
        """

        best_bic = np.inf

        for i in range(num_restarts):

            if verbose:
                print("Random restart", i+1)
            G, convergence = self._discover_admg(data, admg_class, tiers, unconfounded_vars, max_iter,
                                                 h_tol, rho_max, w_threshold, ricf_increment,
                                                 ricf_tol, detailed_output)
            # curr_bic = bic(data, G) # bic function is not available
            curr_bic = 0 # Replace with a placeholder or a different metric if bic is needed
            if verbose:
                print("Estimated di_edges:", G.di_edges)
                print("Estimated bi_edges", G.bi_edges)
                print("BIC", curr_bic)
            if curr_bic < best_bic:
                self.G_ = copy.deepcopy(G)
                self.convergence_ = convergence
                best_bic = curr_bic

        if verbose:
            print("Final estimated di_edges:", self.G_.di_edges)
            print("Final estimated bi_edges", self.G_.bi_edges)
            print("Final BIC", best_bic)

        return self.G_

# function for simulation
def generate_b_from_edges(p, edges):
    """
    Generates a directed adjacency matrix B from a list of directed edges.

    Args:
        p (int): The number of nodes.
        edges (list of tuples): A list of tuples, where each tuple (i, j)
                                 represents a directed edge from node i to node j (0-indexed).

    Returns:
        np.ndarray: The p x p adjacency matrix B.
    """
    B = np.zeros((p, p), dtype=np.float32)
    for i, j in edges:
        # Ensure nodes are within bounds
        if 0 <= i < p and 0 <= j < p and i != j:
             # Weights in [-2, -0.5] or [0.5, 2]
            if np.random.rand() > 0.5:
                weight = np.random.uniform(0.5, 2.0)
            else:
                weight = np.random.uniform(-2.0, -0.5)
            B[i, j] = weight
        else:
            print(f"Warning: Invalid edge ({i}, {j}) for p={p}. Skipping.")

    # Optional: Add a check here to see if the generated graph is acyclic.
    # For this task, we assume the user provides edges that form a DAG.
    # In a real application, you might want to implement a check and potentially raise an error.

    return B

def generate_sigma_from_biedges(p, bidirected_edges, weight_range_diag=(0.7, 1.2), weight_range_offdiag=(-0.7, -0.4, 0.4, 0.7)):
    """
    Generates a symmetric Sigma_e matrix from a list of bidirected edges and diagonal elements.

    Args:
        p (int): The number of nodes.
        bidirected_edges (list of tuples): A list of tuples, where each tuple (i, j)
                                          represents a bidirected edge between node i and node j (0-indexed).
                                          Order doesn't matter, (i, j) is same as (j, i).
        weight_range_diag (tuple): Range for diagonal elements (variances).
        weight_range_offdiag (tuple): Ranges for off-diagonal elements (covariances).

    Returns:
        np.ndarray: The p x p symmetric matrix Sigma_e.
    """
    Sigma_e = np.zeros((p, p), dtype=np.float32)

    # Generate diagonal elements (variances)
    diag_values = np.random.uniform(weight_range_diag[0], weight_range_diag[1], p)
    np.fill_diagonal(Sigma_e, diag_values)

    # Generate off-diagonal elements (covariances) based on bidirected edges
    for i, j in bidirected_edges:
        # Ensure nodes are within bounds and not the same node
        if 0 <= i < p and 0 <= j < p and i != j:
            # Only add the edge once (either (i, j) or (j, i))
            # Decide weight
            if np.random.rand() > 0.5:
                weight = np.random.uniform(weight_range_offdiag[2], weight_range_offdiag[3])
            else:
                weight = np.random.uniform(weight_range_offdiag[0], weight_range_offdiag[1])

            Sigma_e[i, j] = weight
            Sigma_e[j, i] = weight # Ensure symmetry
        else:
            print(f"Warning: Invalid bidirected edge ({i}, {j}) for p={p}. Skipping.")

    return Sigma_e



import math
import random
import numpy as np
import torch


# ============================================================
# 1. 从 BAP 参数 (S, C, B_true, Omega_true) 生成数据
# ============================================================

def simulate_linear_gaussian_bap_data(B_true, Omega_true, n, seed=None, dtype=torch.float64):
    """
    根据线性高斯 BAP/ADMG SEM 生成数据。

    约定：
      B_true[i,j] 表示 i -> j 的系数
      X = E (I - B)^(-1),   E ~ N(0, Omega_true)

    因此协方差为
      Cov(X) = (I - B)^(-T) Omega_true (I - B)^(-1)

    注意：
    这和前面搜索代码里的 log_likelihood 保持一致，因为那里用了
      R = X (I - B)
      即 E = X (I - B)
    """
    if seed is not None:
        np.random.seed(seed)
        random.seed(seed)
        torch.manual_seed(seed)

    B_true = np.asarray(B_true, dtype=np.float64)
    Omega_true = np.asarray(Omega_true, dtype=np.float64)

    d = B_true.shape[0]
    I = np.eye(d, dtype=np.float64)

    ImB = I - B_true
    ImB_inv = np.linalg.inv(ImB)

    # Cov(X) = (I-B)^(-T) Omega (I-B)^(-1)
    Sigma_x = ImB_inv.T @ Omega_true @ ImB_inv

    X = np.random.multivariate_normal(
        mean=np.zeros(d, dtype=np.float64),
        cov=Sigma_x,
        size=n
    )

    return torch.tensor(X, dtype=dtype), Sigma_x

# ============================================================
# 2. 从搜索结果提取估计图的 S, C
# ============================================================

def graph_to_SC(graph, d):
    """
    将 SimpleADMG 对象的 di_edges 和 bi_edges 集合转换为 np 矩阵。
    S[i, j] = 1 表示 i -> j
    C[i, j] = 1 表示 i <-> j
    """
    S = np.zeros((d, d), dtype=int)
    C = np.zeros((d, d), dtype=int)

    # 需要将字符串索引转换为整数索引
    for u, v in graph.di_edges:
        S[int(u), int(v)] = 1

    for u, v in graph.bi_edges:
        C[int(u), int(v)] = 1
        C[int(v), int(u)] = 1

    return S, C

# ============================================================
# 3. 友好的打印函数
# ============================================================

def format_matrix(M, name=None):
    M = np.asarray(M)
    s = np.array2string(M, separator=", ")
    if name is None:
        return s
    return f"{name} =\n{s}"

def print_pag_object(pag, name="PAG"):
    """
    尝试更友好地打印 pag；如果 pag 类自己定义了 __str__，
    直接 print(pag) 即可。
    """
    print(f"{name}:")
    print(pag)

# ============================================================
# 4. 单次实验：生成 GT -> 生成数据 -> BAP 搜索 -> 转 PAG -> 计算指标
# ============================================================

def run_one_experiment(
    exp_id,
    *,
    d,
    n,
    p_dir,
    p_bidir,
    gt_seed=None,
    data_seed=None,
    search_seed=None,
    gt_kwargs=None,
    search_kwargs=None,
    device="cpu",
    dtype=torch.float64,
):
    """
    单次实验流程：
      1) 生成 ground truth
      2) 根据 ground truth 参数生成数据
      3) 用 bap_greedy_search 估计图
      4) GT / estimate 转 PAG
      5) 计算 SHD 等指标
      6) 打印结果
    """
    if gt_kwargs is None:
        gt_kwargs = {}
    if search_kwargs is None:
        search_kwargs = {}

    # ---------------------------
    # (1) 生成 GT
    # ---------------------------
    gt = generate_random_ground_truth_er(
        d=d,
        p_dir=p_dir,
        p_bidir=p_bidir,
        seed=gt_seed,
        **gt_kwargs
    )

    S_true = np.asarray(gt["S_true"]).astype(int)
    C_true = np.asarray(gt["C_true"]).astype(int)
    B_true = np.asarray(gt["B_true"], dtype=np.float64)
    Omega_true = np.asarray(gt["Omega_true"], dtype=np.float64)

    # ---------------------------
    # (2) 生成数据
    # ---------------------------
    X, Sigma_x = simulate_linear_gaussian_bap_data(
        B_true=B_true,
        Omega_true=Omega_true,
        n=n,
        seed=data_seed,
        dtype=dtype,
    )
    X_df = pd.DataFrame(X.detach().cpu().numpy(), columns=[str(i) for i in range(d)])

    # ---------------------------
    # (3) discover admg
    # ---------------------------
    learn = Discovery(lamda=0.05)
    best_G = learn.discover_admg(X_df, admg_class="bowfree", verbose=True)

    S_est, C_est = graph_to_SC(best_G, d)

    # ---------------------------
    # (4) GT / EST 转 PAG
    # ---------------------------
    true_pag = admg_to_pag(p=d, B_mat=S_true, Sigma_mat=C_true)
    est_pag = admg_to_pag(p=d, B_mat=S_est, Sigma_mat=C_est)

    # ---------------------------
    # (5) PAG 指标
    # ---------------------------
    metrics = compute_pag_metrics(true_pag, est_pag)

    # ---------------------------
    # (6) 打印
    # ---------------------------
    print("\n" + "=" * 100)
    print(f"Experiment {exp_id}")
    print("-" * 100)

    print(format_matrix(S_true, "GT S_true"))
    print(format_matrix(C_true, "GT C_true"))
    print()

    print(format_matrix(S_est, "EST S_est"))
    print(format_matrix(C_est, "EST C_est"))
    print()

    print_pag_object(true_pag, name="GT PAG")
    print()
    print_pag_object(est_pag, name="EST PAG")
    print()

    print(f"Metrics = {metrics}")
    print(f"SHD = {metrics['shd']}")

    return {
        "exp_id": exp_id,
        "gt": gt,
        "S_true": S_true,
        "C_true": C_true,
        "S_est": S_est,
        "C_est": C_est,
        "true_pag": true_pag,
        "est_pag": est_pag,
        "metrics": metrics,
    }

# ============================================================
# 5. 多次实验并汇总平均 SHD
# ============================================================

def run_bap_pag_benchmark(
    *,
    n_experiments=10,
    d=5,
    n=500,
    p_dir=0.2,
    p_bidir=0.1,
    gt_seed_base=1000,
    data_seed_base=2000,
    search_seed_base=3000,
    gt_kwargs=None,
    search_kwargs=None,
    device="cpu",
    dtype=torch.float64,
):
    if gt_kwargs is None:
        gt_kwargs = {}
    if search_kwargs is None:
        search_kwargs = {}

    all_results = []
    shd_list = []

    for t in range(n_experiments):
        result_t = run_one_experiment(
            exp_id=t + 1,
            d=d,
            n=n,
            p_dir=p_dir,
            p_bidir=p_bidir,
            gt_seed=gt_seed_base + t if gt_seed_base is not None else None,
            data_seed=data_seed_base + t if data_seed_base is not None else None,
            search_seed=search_seed_base + t if search_seed_base is not None else None,
            gt_kwargs=gt_kwargs,
            search_kwargs=search_kwargs,
            device=device,
            dtype=dtype,
        )

        all_results.append(result_t)
        shd_list.append(float(result_t["metrics"]["shd"]))

    mean_shd = float(np.mean(shd_list)) if len(shd_list) > 0 else float("nan")
    std_shd = float(np.std(shd_list)) if len(shd_list) > 0 else float("nan")

    print("\n" + "#" * 100)
    print("Summary over all experiments")
    print("#" * 100)
    print(f"Number of experiments = {n_experiments}")
    print(f"SHD list = {shd_list}")
    print(f"Average SHD = {mean_shd:.6f}")
    print(f"Std SHD = {std_shd:.6f}")

    return {
        "all_results": all_results,
        "shd_list": shd_list,
        "mean_shd": mean_shd,
        "std_shd": std_shd,
    }

# ============================================================
# 6. 使用示例
# ============================================================

if __name__ == "__main__":

    gt_kwargs = dict(
        B_abs_low=0.3,
        B_abs_high=1.5,
        Omega_diag_low=1.0,
        Omega_diag_high=2.0,
        Omega_off_abs_low=0.1,
        Omega_off_abs_high=0.6,
        B_allow_negative=True,
        Omega_allow_negative=True,
        spd_floor=1e-3,
    )

    summary = run_bap_pag_benchmark(
        n_experiments=10,
        d=5,
        n=1000,
        p_dir=0.40,
        p_bidir=0.20,
        gt_seed_base=2026,
        data_seed_base=2027,
        search_seed_base=2028,
        gt_kwargs=gt_kwargs,
        search_kwargs=None,
        device="cpu",
        dtype=torch.float64,
    )

# if __name__ == "__main__":
#
#     # example usage
#     #np.random.seed(41)
#     size = 1000
#     dim = 4
#
#     # Define directed and bidirected edges based on user's request
#     edges = [(2, 1), (2, 3), (0, 3),(3, 1)]
#     biedges = [(0, 1)]
#
#     # Generate beta and omega from the defined edges
#     beta = generate_b_from_edges(dim, edges)
#     omega = generate_sigma_from_biedges(dim, biedges)
#
#     print("Generated Beta Matrix:\n", beta)
#     print("Generated Omega Matrix:\n", omega)
#
#     # DGP A->B->C->D; B<->D ab,ac,ad,db, cd
#     # beta = np.array([[0, 0, -0.84, 0],
#     #           [0, 0, 0, 0],
#     #           [0, 0, 0, 0],
#     #           [0, 0, 0, 0]]).T
#
#     # omega = np.array([[1.13,0.42,-0.61,0],
#     #           [0.42,0.96,0.62,0.69],
#     #         [-0.61  0.62  1.18  0.64]
#     #  [ 0.    0.69  0.64  1.18]])
#
#     # generate data according to the graph
#     true_sigma = np.linalg.inv(np.eye(dim) - beta) @ omega @ np.linalg.inv((np.eye(dim) - beta).T)
#     X = np.random.multivariate_normal([0] * dim, true_sigma, size=size)
#     X = X - np.mean(X, axis=0)  # centre the data
#
#     data = pd.DataFrame({"0": X[:, 0], "1": X[:, 1], "2": X[:, 2], "3": X[:, 3]})
#
#     learn = Discovery(lamda=0.05)
#     best_G = learn.discover_admg(data, admg_class="bowfree", verbose=True)
#     print(learn.convergence_)
#     print(learn.G_.di_edges)
#     print(learn.G_.bi_edges)

# # 3. 完整流程示例
# # ==========================================
#
# # 设置节点数
#
# gt = generate_random_ground_truth_er(
#     d=5,
#     p_dir=0.5,
#     p_bidir=0.5,
#     seed=42,
# )
# true_pag = admg_to_pag(p, gt_di, gt_bi)
# print(f"Ground Truth PAG Generated.")
#
# # --- ABIC 结果整理 (将你的文本转换为列表) ---
# # 注意：你的文本中有些数字是字符串 '3'，有些是 int。这里统一处理为 int。
# # ABIC 输出是 edge list，可以直接输入 admg_to_pag
#
# results_data = {
#     "Restart 1": {
#         "di": [(3, 0), (0, 2), (1, 2)],
#         "bi": [(1, 3), (2, 3), (0, 1)]
#     },
#     "Restart 2": {
#         "di": [(3, 0), (2, 1)],
#         "bi": [(2, 3), (0, 2), (0, 1)]
#     },
#     "Restart 3": {
#         "di": [(1, 3), (3, 2), (1, 2)],
#         "bi": [(0, 3)]
#     },
#     "Restart 4": {
#         "di": [(1, 3), (3, 2), (1, 2)],
#         "bi": [(0, 3)]
#     },
#     "Restart 5": {
#         "di": [(1, 3), (3, 2), (1, 2), (3, 0)],
#         "bi": [(0, 1)]
#     }
# }
#
# print("\n--- Metrics Calculation Results ---\n")
# print(f"{'Experiment':<15} | {'SHD':<5} | {'Skel F1':<8} | {'Arrow F1':<8}")
# print("-" * 50)
# total_shd = 0
# total_skel_f1 = 0
# total_arrow_f1 = 0
# for name, res in results_data.items():
#     # 1. 转换 Est ADMG -> Est PAG
#     est_pag = admg_to_pag(p, res['di'], res['bi'])
#
#     # 2. 计算指标
#     metrics = compute_pag_metrics(true_pag, est_pag)
#
#     # 3. 打印
#     print(f"{name:<15} | {metrics['shd']:<5} | {metrics['f1_skeleton']:<8} | {metrics['f1_arrowhead']:<8}")
#     # 4. 计算均值
#     total_shd += metrics['shd']
#     total_skel_f1 += metrics['f1_skeleton']
#     total_arrow_f1 += metrics['f1_arrowhead']
# # 可选：打印 Final 的详细信息，用于调试
# print("\n[Detailed Final Result]")
# print(total_shd/5)
# print(total_skel_f1/5)
# print(total_arrow_f1/5)
