# -*- coding: utf-8 -*-
"""greedyBAP_ricf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CNzH41nhe2AA-27-DOmdOum1DZKZlDMR
"""

import math
import random
import copy
from dataclasses import dataclass
from typing import List, Tuple, Optional, Dict, Any

import numpy as np
import torch
import torch.nn as nn

import torch.optim as optim
#!pip install python-igraph
#!pip install causal-learn
import igraph as ig
from causallearn.graph.Dag import Dag
from causallearn.graph.GraphNode import GraphNode
from causallearn.utils.DAG2PAG import dag2pag
from causallearn.graph.Endpoint import Endpoint

# ============================================================
# Ground-truth generation by ER graphs
# ============================================================

def _graph_to_adjmat(G):
    return np.array(G.get_adjacency().data, dtype=np.float64)

def simulate_er_dag_igraph(d: int, p_edge: float, rng=None):
    """
    用 igraph 生成 ER 无向图，再随机赋予一个拓扑顺序，定向成 DAG。
    约定: S[i,j]=1 表示 i -> j
    """
    if rng is None:
        rng = np.random.default_rng()

    p_edge = float(np.clip(p_edge, 0.0, 1.0))
    G_und = ig.Graph.Erdos_Renyi(n=d, p=p_edge, directed=False, loops=False)
    A_und = _graph_to_adjmat(G_und)

    perm = rng.permutation(d)
    pos = np.empty(d, dtype=int)
    pos[perm] = np.arange(d)

    S = np.zeros((d, d), dtype=np.float64)
    for i in range(d):
        for j in range(i + 1, d):
            if A_und[i, j] != 0:
                if pos[i] < pos[j]:
                    S[i, j] = 1.0
                else:
                    S[j, i] = 1.0
    return S

def simulate_er_bidirected_igraph(d: int, p_edge: float, rng=None):
    """
    用 igraph 生成无向 ER 图作为 bidirected 结构。
    返回对称 0/1 矩阵 C，且对角线为 1。
    """
    if rng is None:
        rng = np.random.default_rng()

    p_edge = float(np.clip(p_edge, 0.0, 1.0))
    G = ig.Graph.Erdos_Renyi(n=d, p=p_edge, directed=False, loops=False)
    A = _graph_to_adjmat(G)

    C = ((A + A.T) > 0).astype(np.float64)
    np.fill_diagonal(C, 1.0)
    return C

def sample_weighted_B_from_S(
    S,
    rng=None,
    abs_low=0.3,
    abs_high=1.5,
    allow_negative=True,
):
    """
    根据 0/1 结构矩阵 S 生成 weighted B_true.
    约定: B[i,j] 表示 i -> j
    """
    if rng is None:
        rng = np.random.default_rng()

    d = S.shape[0]
    B = np.zeros((d, d), dtype=np.float64)

    rows, cols = np.where(S != 0)
    for i, j in zip(rows, cols):
        mag = rng.uniform(abs_low, abs_high)
        sign = rng.choice([-1.0, 1.0]) if allow_negative else 1.0
        B[i, j] = sign * mag

    return B

def sample_weighted_Omega_from_C(
    C,
    rng=None,
    diag_low=1.0,
    diag_high=2.0,
    off_abs_low=0.1,
    off_abs_high=0.6,
    allow_negative=True,
    spd_floor=1e-3,
):
    """
    根据 0/1 结构矩阵 C 生成 weighted Omega_true.
    - 对角线随机正值
    - C[i,j]=1 的非对角位置给随机权重
    - 最后通过最小特征值修正保证正定:
          Omega <- Omega + soft_shift * I
      这里直接用线性 shift:
          shift = max(0, spd_floor - lambda_min)
    """
    if rng is None:
        rng = np.random.default_rng()

    d = C.shape[0]
    Omega = np.zeros((d, d), dtype=np.float64)

    diag_vals = rng.uniform(diag_low, diag_high, size=d)
    np.fill_diagonal(Omega, diag_vals)

    for i in range(d):
        for j in range(i + 1, d):
            if C[i, j] != 0:
                mag = rng.uniform(off_abs_low, off_abs_high)
                sign = rng.choice([-1.0, 1.0]) if allow_negative else 1.0
                val = sign * mag
                Omega[i, j] = val
                Omega[j, i] = val

    eigvals = np.linalg.eigvalsh(Omega)
    lam_min = eigvals.min()
    shift = max(0.0, spd_floor - lam_min)
    if shift > 0:
        Omega = Omega + shift * np.eye(d, dtype=np.float64)

    return Omega

def generate_random_ground_truth_er(
    d,
    p_dir,
    p_bidir,
    seed=None,
    B_abs_low=0.3,
    B_abs_high=1.5,
    Omega_diag_low=1.0,
    Omega_diag_high=2.0,
    Omega_off_abs_low=0.1,
    Omega_off_abs_high=0.6,
    B_allow_negative=True,
    Omega_allow_negative=True,
    spd_floor=1e-3,
):
    """
    一次性生成:
      - S_true: ER DAG 结构
      - C_true: ER bidirected 结构
      - B_true: 根据 S_true 加权
      - Omega_true: 根据 C_true 加权并修正为 SPD
    """
    rng = np.random.default_rng(seed)

    S_true = simulate_er_dag_igraph(d=d, p_edge=p_dir, rng=rng)
    C_true = simulate_er_bidirected_igraph(d=d, p_edge=p_bidir, rng=rng)

    B_true = sample_weighted_B_from_S(
        S_true,
        rng=rng,
        abs_low=B_abs_low,
        abs_high=B_abs_high,
        allow_negative=B_allow_negative,
    )

    Omega_true = sample_weighted_Omega_from_C(
        C_true,
        rng=rng,
        diag_low=Omega_diag_low,
        diag_high=Omega_diag_high,
        off_abs_low=Omega_off_abs_low,
        off_abs_high=Omega_off_abs_high,
        allow_negative=Omega_allow_negative,
        spd_floor=spd_floor,
    )

    return {
        "d": d,
        "S_true": S_true,
        "C_true": C_true,
        "B_true": B_true,
        "Omega_true": Omega_true,
    }


# ============================================================
# 0. Fixed convention
# ============================================================
# S[i,j] = 1 means i -> j
# B[i,j] != 0 means i -> j
# fixed topological order: only i < j directed edges are allowed


# ============================================================
# 2. Data simulation
# ============================================================

def simulate_linear_scm_i_to_j(n, B, Omega, seed=42):
    """
    X = E (I - B)^(-1), where B[i,j] means i -> j.
    """
    rng = np.random.default_rng(seed)
    p = B.shape[0]
    L = np.linalg.cholesky(Omega)
    E = rng.standard_normal((n, p)) @ L.T
    X = E @ np.linalg.inv(np.eye(p) - B)
    return X


# ============================================================
# 3. SHD
# ============================================================

def admg_to_pag(p, edges=None, biedges=None, B_mat=None, Sigma_mat=None):
    """
    将 ADMG 转换为 PAG
    参数:
    - p: 观测变量的数量 (int)
    - edges: 有向边列表, 如 [(0, 2)]
    - biedges: 双向边列表, 如 [(0, 1), (1, 2)]
    - B_mat: 有向边权重矩阵 (可选)
    - Sigma_mat: 噪声协方差矩阵 (可选)
    """

    # 1. 初始化观测变量节点
    nodes = [GraphNode(str(i)) for i in range(p)]
    all_nodes = list(nodes)
    latent_nodes = []

    # 2. 创建一个空的 DAG 对象
    # 注意：dag2pag 需要输入一个包含显变量和隐变量的完整 DAG
    dag = Dag(all_nodes)

    # 3. 处理有向边 (Directed Edges)
    if B_mat is not None:
        # 从矩阵提取有向边 (B_ij 表示 i -> j)
        for i in range(p):
            for j in range(p):
                if B_mat[i, j] != 0:
                    dag.add_directed_edge(nodes[i], nodes[j])
    elif edges is not None:
        for i, j in edges:
            dag.add_directed_edge(nodes[i], nodes[j])

    # 4. 处理双向边 (Bidirected Edges) -> 转换为隐变量结构
    # 每条双向边 i <-> j 变成 L -> i 和 L -> j
    if Sigma_mat is not None:
        # 从矩阵提取双向边 (只看上三角，排除对角线)
        for i in range(p):
            for j in range(i + 1, p):
                if Sigma_mat[i, j] != 0:
                    # 创建新的隐变量节点
                    l_node = GraphNode(f"L_{i}_{j}")
                    dag.add_node(l_node)
                    latent_nodes.append(l_node)
                    # 添加从隐变量到两个观测点的有向边
                    dag.add_directed_edge(l_node, nodes[i])
                    dag.add_directed_edge(l_node, nodes[j])
    elif biedges is not None:
        for i, j in biedges:
            l_node = GraphNode(f"L_{i}_{j}")
            dag.add_node(l_node)
            latent_nodes.append(l_node)
            dag.add_directed_edge(l_node, nodes[i])
            dag.add_directed_edge(l_node, nodes[j])

    # 5. 调用 causal-learn 函数将 DAG 转为 PAG
    # 第二个参数是需要 marginalize 掉的隐变量列表
    pag = dag2pag(dag, latent_nodes)

    return pag

def compute_pag_metrics(true_pag, est_pag):
    """
    计算 SHD, Skeleton F1, Arrowhead F1
    基于 causal-learn 的 GeneralGraph 对象
    """
    # 获取邻接矩阵 (graph property stores the matrix)
    # causal-learn 矩阵定义: M[i, j] 表示 i 和 j 之间在 j 端点的类型
    # 0: No Edge, 1: Circle, 2: Arrow, 3: Tail

    true_adj = true_pag.graph
    est_adj = est_pag.graph
    p = true_adj.shape[0]

    # --- 1. Skeleton F1 ---
    # 只需要看是否有边 (非0)，只遍历上三角避免重复
    tp_skel = 0
    fp_skel = 0
    fn_skel = 0

    for i in range(p):
        for j in range(i + 1, p):
            has_edge_true = (true_adj[i, j] != 0)
            has_edge_est = (est_adj[i, j] != 0)

            if has_edge_true and has_edge_est:
                tp_skel += 1
            elif not has_edge_true and has_edge_est:
                fp_skel += 1
            elif has_edge_true and not has_edge_est:
                fn_skel += 1

    precision_skel = tp_skel / (tp_skel + fp_skel) if (tp_skel + fp_skel) > 0 else 0
    recall_skel = tp_skel / (tp_skel + fn_skel) if (tp_skel + fn_skel) > 0 else 0
    f1_skel = 2 * precision_skel * recall_skel / (precision_skel + recall_skel) if (precision_skel + recall_skel) > 0 else 0

    # --- 2. Arrowhead F1 ---
    # 统计所有箭头 (Arrow = 2) 的预测情况
    # 遍历整个矩阵 (包括 i,j 和 j,i)，因为箭头是有方向的
    tp_arrow = 0
    fp_arrow = 0
    fn_arrow = 0

    # ARROW 在 causal-learn Endpoint 中通常对应值 2
    ARROW_MARK = Endpoint.ARROW.value

    for i in range(p):
        for j in range(p):
            if i == j: continue

            # True PAG 在 j 处是否有箭头
            is_arrow_true = (true_adj[i, j] == ARROW_MARK)
            # Est PAG 在 j 处是否有箭头
            is_arrow_est = (est_adj[i, j] == ARROW_MARK)

            if is_arrow_true and is_arrow_est:
                tp_arrow += 1
            elif not is_arrow_true and is_arrow_est:
                fp_arrow += 1
            elif is_arrow_true and not is_arrow_est:
                fn_arrow += 1

    precision_arrow = tp_arrow / (tp_arrow + fp_arrow) if (tp_arrow + fp_arrow) > 0 else 0
    recall_arrow = tp_arrow / (tp_arrow + fn_arrow) if (tp_arrow + fn_arrow) > 0 else 0
    f1_arrow = 2 * precision_arrow * recall_arrow / (precision_arrow + recall_arrow) if (precision_arrow + recall_arrow) > 0 else 0

    # --- 3. SHD (Structural Hamming Distance) ---
    # 定义：增加/删除边 + 修改端点方向的操作总数
    # 策略：
    # - 边存在性不同: SHD + 1

    shd = 0
    for i in range(p):
        for j in range(i + 1, p):
            diff = (true_adj[i,j]!=est_adj[i,j]) or (true_adj[j,i]!=est_adj[j,i])
            if diff:
                shd += 1.0

    return {
        "shd": int(shd) if shd.is_integer() else shd,
        "f1_skeleton": round(f1_skel, 4),
        "f1_arrowhead": round(f1_arrow, 4),
        "precision_arrow": round(precision_arrow, 4),
        "recall_arrow": round(recall_arrow, 4)
    }

# ============================================================
# 1. Graph representation for BAP
# ============================================================

@dataclass
class BAPGraph:
    """
    D[i,j] = 1 means i -> j
    C[i,j] = C[j,i] = 1 means i <-> j
    Diagonal of D and C must be zero.
    """
    D: np.ndarray  # shape [d,d], dtype bool/int
    C: np.ndarray  # shape [d,d], symmetric, zero diagonal

    def copy(self):
        return BAPGraph(self.D.copy(), self.C.copy())

    @property
    def d(self):
        return self.D.shape[0]

    def num_directed_edges(self):
        return int(self.D.sum())

    def num_bidirected_edges(self):
        return int(np.triu(self.C, k=1).sum())

    def num_edges(self):
        return self.num_directed_edges() + self.num_bidirected_edges()

    def validate(self):
        d = self.d
        assert self.D.shape == (d, d)
        assert self.C.shape == (d, d)
        assert np.all(np.diag(self.D) == 0), "D diagonal must be zero"
        assert np.all(np.diag(self.C) == 0), "C diagonal must be zero"
        assert np.all(self.C == self.C.T), "C must be symmetric"
        # bow-free
        assert np.all((self.D + self.D.T + self.C) <= 1), "bow-free violated"
        # acyclic directed part
        assert is_acyclic(self.D), "Directed part must be acyclic"

    def key(self):
        return (self.D.astype(np.uint8).tobytes(), self.C.astype(np.uint8).tobytes())

def empty_bap(d: int) -> BAPGraph:
    return BAPGraph(
        D=np.zeros((d, d), dtype=np.uint8),
        C=np.zeros((d, d), dtype=np.uint8),
    )

# ============================================================
# 2. Basic graph utilities
# ============================================================

def is_acyclic(D: np.ndarray) -> bool:
    """
    Check acyclicity of directed adjacency matrix D using Kahn's algorithm.
    D[i,j]=1 means i -> j
    """
    d = D.shape[0]
    indeg = D.sum(axis=0).astype(int).tolist()
    queue = [i for i in range(d) if indeg[i] == 0]
    visited = 0

    # outgoing from i are D[i,:]
    while queue:
        v = queue.pop()
        visited += 1
        children = np.where(D[v] != 0)[0]
        for ch in children:
            indeg[ch] -= 1
            if indeg[ch] == 0:
                queue.append(ch)

    return visited == d

def can_add_directed_edge(D: np.ndarray, i: int, j: int) -> bool:
    """
    Whether adding i -> j keeps the directed part acyclic.
    """
    if i == j:
        return False
    if D[i, j] == 1:
        return False

    D_new = D.copy()
    D_new[i, j] = 1
    return is_acyclic(D_new)

def has_any_edge(G: BAPGraph, i: int, j: int) -> bool:
    """
    Whether the unordered pair {i,j} has any edge.
    """
    return (G.D[i, j] == 1) or (G.D[j, i] == 1) or (G.C[i, j] == 1)

def edge_state(G: BAPGraph, i: int, j: int) -> str:
    """
    For i < j:
      "none"
      "i->j"
      "j->i"
      "bi"
    """
    assert i < j
    if G.D[i, j] == 1:
        return "i->j"
    elif G.D[j, i] == 1:
        return "j->i"
    elif G.C[i, j] == 1:
        return "bi"
    else:
        return "none"

def set_edge_state(G: BAPGraph, i: int, j: int, state: str) -> BAPGraph:
    """
    Return a new graph with the unordered pair {i,j} set to the given state.
    i < j
    """
    assert i < j
    H = G.copy()

    # clear current state on pair {i,j}
    H.D[i, j] = 0
    H.D[j, i] = 0
    H.C[i, j] = 0
    H.C[j, i] = 0

    if state == "none":
        pass
    elif state == "i->j":
        H.D[i, j] = 1
    elif state == "j->i":
        H.D[j, i] = 1
    elif state == "bi":
        H.C[i, j] = 1
        H.C[j, i] = 1
    else:
        raise ValueError(f"Unknown state: {state}")

    # validity checks
    if not np.all((H.D + H.D.T + H.C) <= 1):
        raise ValueError("Bow-free violated after edge assignment.")
    if not is_acyclic(H.D):
        raise ValueError("Directed cycle created.")

    return H

def all_local_neighbors(G: BAPGraph) -> List[BAPGraph]:
    """
    Local neighborhood used in greedy hill climbing.

    For each unordered pair {i,j}, possible states are:
      none, i->j, j->i, bi
    and we allow changing to any other valid state differing by one local edit.
    """
    d = G.d
    neighbors = []
    seen = set()

    for i in range(d):
        for j in range(i + 1, d):
            cur = edge_state(G, i, j)
            candidates = ["none", "i->j", "j->i", "bi"]

            for new_state in candidates:
                if new_state == cur:
                    continue
                try:
                    H = set_edge_state(G, i, j, new_state)
                    key = H.key()
                    if key not in seen:
                        seen.add(key)
                        neighbors.append(H)
                except ValueError:
                    pass

    return neighbors

# ============================================================
# 3. Uniform random BAP generation via MCMC-style restart
#    (following the paper's idea)
# ============================================================

def random_bap_mcmc(
    d: int,
    burnin: int = 500,
    seed: Optional[int] = None,
    start_graph: Optional[BAPGraph] = None,
) -> BAPGraph:
    """
    Approximate uniform random restart graph using the paper's MCMC-style idea.
    """
    rng = random.Random(seed)

    if start_graph is None:
        G = empty_bap(d)
    else:
        G = start_graph.copy()

    for _ in range(burnin):
        i = rng.randrange(d)
        j = rng.randrange(d - 1)
        if j >= i:
            j += 1

        sigma = rng.random() < 0.5

        a, b = min(i, j), max(i, j)
        current_has_edge = has_any_edge(G, a, b)

        if current_has_edge:
            # if edge exists:
            #   sigma=0 => delete
            #   sigma=1 => keep
            if not sigma:
                G = set_edge_state(G, a, b, "none")
        else:
            # if no edge:
            #   sigma=0 => try add directed i -> j
            #   sigma=1 => add bidirected
            if not sigma:
                # note: use ordered pair (i,j)
                H = G.copy()
                if G.C[i, j] == 0 and G.C[j, i] == 0 and G.D[j, i] == 0 and G.D[i, j] == 0:
                    H.D[i, j] = 1
                    if is_acyclic(H.D):
                        G = H
            else:
                H = G.copy()
                if H.D[a, b] == 0 and H.D[b, a] == 0:
                    H.C[a, b] = 1
                    H.C[b, a] = 1
                    G = H

    G.validate()
    return G

# ============================================================
# 8. Pretty-print helpers
# ============================================================

def graph_to_string(G: BAPGraph) -> str:
    d = G.d
    directed = []
    bidirected = []
    for i in range(d):
        for j in range(d):
            if G.D[i, j] == 1:
                directed.append(f"{i}->{j}")
    for i in range(d):
        for j in range(i + 1, d):
            if G.C[i, j] == 1:
                bidirected.append(f"{i}<->{j}")
    return (
        f"Directed: {directed}\n"
        f"Bidirected: {bidirected}\n"
        f"#dir={G.num_directed_edges()}, #bi={G.num_bidirected_edges()}, #total={G.num_edges()}"
    )

import math
import random
import numpy as np

# ============================================================
# 1. 数值工具
# ============================================================

def center_data_np(X):
    """
    Center data column-wise.
    """
    X = np.asarray(X, dtype=np.float64)
    return X - X.mean(axis=0, keepdims=True)

def safe_slogdet(A, jitter=1e-10, max_tries=8):
    """
    Stable slogdet with diagonal jitter if needed.
    """
    A = np.asarray(A, dtype=np.float64)
    d = A.shape[0]

    for k in range(max_tries):
        Aj = A + (jitter * (10 ** k)) * np.eye(d)
        sign, logdet = np.linalg.slogdet(Aj)
        if sign > 0 and np.isfinite(logdet):
            return sign, logdet, Aj

    sign, logdet = np.linalg.slogdet(A)
    return sign, logdet, A

def safe_inverse_spd(A, jitter=1e-10, max_tries=8):
    """
    Invert SPD-like matrix with jitter.
    """
    A = np.asarray(A, dtype=np.float64)
    d = A.shape[0]

    for k in range(max_tries):
        Aj = A + (jitter * (10 ** k)) * np.eye(d)
        try:
            np.linalg.cholesky(Aj)
            return np.linalg.inv(Aj)
        except np.linalg.LinAlgError:
            pass

    return np.linalg.pinv(A)

def solve_ridge_lstsq(A, y, ridge=1e-10):
    """
    Solve min ||y - A theta||^2 with tiny ridge stabilization.

    A: [n, q]
    y: [n]
    """
    A = np.asarray(A, dtype=np.float64)
    y = np.asarray(y, dtype=np.float64)

    q = A.shape[1]
    if q == 0:
        return np.zeros(0, dtype=np.float64)

    AtA = A.T @ A
    Aty = A.T @ y

    return np.linalg.solve(
        AtA + ridge * np.eye(q),
        Aty
    )

def make_spd_by_jitter(A, jitter=1e-8, max_tries=12):
    """
    Return A + eps I that is numerically SPD.
    """
    A = np.asarray(A, dtype=np.float64)
    d = A.shape[0]

    A = 0.5 * (A + A.T)

    for k in range(max_tries):
        eps = jitter * (10 ** k)
        Aj = A + eps * np.eye(d)
        try:
            np.linalg.cholesky(Aj)
            return Aj
        except np.linalg.LinAlgError:
            pass

    eigvals = np.linalg.eigvalsh(A)
    min_eig = eigvals.min()
    shift = max(jitter, -min_eig + jitter)
    return A + shift * np.eye(d)

# ============================================================
# 2. RICF 初始化
# ============================================================

def initialize_bap_parameters_ricf(X, graph, ridge=1e-10, min_var=1e-8):
    """
    Initialize B and Omega for a fixed BAP graph.

    Convention:
      graph.D[i,j] = 1 means i -> j
      graph.C[i,j] = 1 means i <-> j

    Model convention:
      E = X (I - B)
      e_j = x_j - sum_i x_i B[i,j]
    """
    X = center_data_np(X)
    n, d = X.shape

    D = np.asarray(graph.D).astype(int)
    C = np.asarray(graph.C).astype(int)

    B = np.zeros((d, d), dtype=np.float64)

    # Initial B by OLS node-wise on directed parents.
    for j in range(d):
        pa = np.where(D[:, j] == 1)[0]

        if len(pa) > 0:
            A = X[:, pa]
            y = X[:, j]
            beta = solve_ridge_lstsq(A, y, ridge=ridge)
            B[pa, j] = beta

    # Residuals under initial B.
    I = np.eye(d)
    E = X @ (I - B)

    # Safe initial Omega:
    # Use diagonal residual variances only.
    Omega = np.zeros((d, d), dtype=np.float64)

    for j in range(d):
        var_j = float(np.mean(E[:, j] ** 2))
        Omega[j, j] = max(var_j, min_var)

    # Optional mild initialization for bidirected entries.
    # This can help, but may break SPD if too large.
    # We therefore shrink if necessary.
    Omega_candidate = Omega.copy()
    for i in range(d):
        for j in range(i):
            if C[i, j] == 1:
                cov_ij = float(np.mean(E[:, i] * E[:, j]))
                Omega_candidate[i, j] = cov_ij
                Omega_candidate[j, i] = cov_ij

    Omega_candidate = 0.5 * (Omega_candidate + Omega_candidate.T)

    try:
        np.linalg.cholesky(Omega_candidate)
        Omega = Omega_candidate
    except np.linalg.LinAlgError:
        # fall back to diagonal Omega
        pass

    Omega = make_spd_by_jitter(Omega, jitter=min_var)

    return B, Omega

# ============================================================
# 3. 固定图 RICF 拟合
# ============================================================

def fit_bap_ricf(
    X,
    graph,
    *,
    max_iter=100,
    tol=1e-6,
    ridge=1e-10,
    min_var=1e-8,
    jitter=1e-10,
    verbose=False,
):
    """
    RICF fitting for a fixed BAP graph.

    This is a residual iterative conditional fitting style implementation.

    Fixed graph constraints:
      - B[i,j] free only if i -> j exists.
      - Omega[i,j] free only if i <-> j exists or i == j.

    Returns:
      {
        "B": B_hat,
        "Omega": Omega_hat,
        "converged": bool,
        "n_iter": int,
        "max_change": float
      }
    """
    graph.validate()

    X = center_data_np(X)
    n, d = X.shape

    D = np.asarray(graph.D).astype(int)
    C = np.asarray(graph.C).astype(int)

    B, Omega = initialize_bap_parameters_ricf(
        X,
        graph,
        ridge=ridge,
        min_var=min_var,
    )

    I = np.eye(d)

    converged = False
    last_max_change = np.inf

    for it in range(max_iter):
        B_old = B.copy()
        Omega_old = Omega.copy()

        for v in range(d):
            pa = np.where(D[:, v] == 1)[0]
            sp = np.where(C[:, v] == 1)[0]

            minus_v = np.array([k for k in range(d) if k != v], dtype=int)

            # Recompute residuals using latest B.
            E = X @ (I - B)

            Omega_minus = Omega[np.ix_(minus_v, minus_v)]
            Omega_minus_inv = safe_inverse_spd(
                Omega_minus,
                jitter=jitter,
            )

            y = X[:, v]

            design_parts = []

            # Directed parent design: X_pa
            if len(pa) > 0:
                X_pa = X[:, pa]
                design_parts.append(X_pa)

            # Spouse pseudo-variable design.
            # Conditional mean part:
            #   E[e_v | e_-v]
            # = Omega[v,-v] Omega[-v,-v]^{-1} e_-v
            #
            # Since Omega[v,-v] is only nonzero on spouses,
            # define Z_sp = E_-v @ Omega[-v,-v]^{-1}[:, spouse_positions]
            # and regress coefficient is Omega[sp, v].
            if len(sp) > 0:
                sp_pos = np.array(
                    [np.where(minus_v == s)[0][0] for s in sp],
                    dtype=int
                )

                E_minus = E[:, minus_v]
                Z_sp = E_minus @ Omega_minus_inv[:, sp_pos]
                design_parts.append(Z_sp)
            else:
                sp_pos = np.array([], dtype=int)

            if len(design_parts) > 0:
                A = np.column_stack(design_parts)
                theta = solve_ridge_lstsq(A, y, ridge=ridge)
                residual = y - A @ theta
            else:
                theta = np.zeros(0, dtype=np.float64)
                residual = y.copy()

            # Parse regression coefficients.
            offset = 0

            beta_pa = np.zeros(len(pa), dtype=np.float64)
            if len(pa) > 0:
                beta_pa = theta[offset:offset + len(pa)]
                offset += len(pa)

            omega_sp = np.zeros(len(sp), dtype=np.float64)
            if len(sp) > 0:
                omega_sp = theta[offset:offset + len(sp)]
                offset += len(sp)

            # Update B column v.
            B[:, v] = 0.0
            if len(pa) > 0:
                B[pa, v] = beta_pa

            # Update Omega row/column v.
            # Preserve Omega[-v,-v], update conditional covariance block.
            Omega[v, :] = 0.0
            Omega[:, v] = 0.0

            if len(sp) > 0:
                Omega[v, sp] = omega_sp
                Omega[sp, v] = omega_sp

            delta_v = float(np.mean(residual ** 2))
            delta_v = max(delta_v, min_var)

            if len(sp) > 0:
                K_ss = Omega_minus_inv[np.ix_(sp_pos, sp_pos)]
                omega_quad = float(omega_sp.T @ K_ss @ omega_sp)
            else:
                omega_quad = 0.0

            Omega[v, v] = delta_v + omega_quad

            # Numerical symmetrization.
            Omega = 0.5 * (Omega + Omega.T)

            # The RICF update should preserve SPD if Omega[-v,-v] is SPD
            # and delta_v > 0. Add tiny jitter for numerical safety.
            Omega = make_spd_by_jitter(Omega, jitter=min_var)

        max_change_B = float(np.max(np.abs(B - B_old)))
        max_change_Om = float(np.max(np.abs(Omega - Omega_old)))
        last_max_change = max(max_change_B, max_change_Om)

        if verbose:
            print(
                f"[RICF] iter={it + 1:03d}, "
                f"max_change={last_max_change:.3e}, "
                f"change_B={max_change_B:.3e}, "
                f"change_Omega={max_change_Om:.3e}"
            )

        if last_max_change < tol:
            converged = True
            break

    # Final cleanup according to graph constraints.
    B = B * D

    Omega_clean = np.zeros_like(Omega)
    np.fill_diagonal(Omega_clean, np.diag(Omega))
    for i in range(d):
        for j in range(i):
            if C[i, j] == 1:
                Omega_clean[i, j] = Omega[i, j]
                Omega_clean[j, i] = Omega[j, i]

    Omega_clean = make_spd_by_jitter(Omega_clean, jitter=min_var)

    return {
        "B": B,
        "Omega": Omega_clean,
        "converged": converged,
        "n_iter": it + 1,
        "max_change": last_max_change,
    }

# ============================================================
# 4. Gaussian log-likelihood
# ============================================================

def gaussian_sem_loglik_from_B_Omega(
    X,
    B,
    Omega,
    *,
    center=True,
    jitter=1e-10,
):
    """
    Gaussian SEM log-likelihood using the residual form.

    Convention:
      B[i,j] means i -> j.
      E = X (I - B).
      E ~ N(0, Omega).

    Therefore:
      log L =
        n log |det(I-B)|
        - n/2 log |Omega|
        - 1/2 tr(E Omega^{-1} E^T)
        - nd/2 log(2pi)
    """
    X = np.asarray(X, dtype=np.float64)
    if center:
        X = center_data_np(X)

    B = np.asarray(B, dtype=np.float64)
    Omega = np.asarray(Omega, dtype=np.float64)

    n, d = X.shape
    I = np.eye(d)

    ImB = I - B

    sign_imb, logdet_imb = np.linalg.slogdet(ImB)
    if sign_imb <= 0 or not np.isfinite(logdet_imb):
        return -np.inf

    sign_om, logdet_om, Omega_used = safe_slogdet(
        Omega,
        jitter=jitter,
    )
    if sign_om <= 0 or not np.isfinite(logdet_om):
        return -np.inf

    E = X @ ImB

    Omega_inv = safe_inverse_spd(
        Omega_used,
        jitter=jitter,
    )

    quad = float(np.einsum("ni,ij,nj->", E, Omega_inv, E))

    ll = (
        n * logdet_imb
        - 0.5 * n * logdet_om
        - 0.5 * quad
        - 0.5 * n * d * math.log(2.0 * math.pi)
    )

    if not np.isfinite(ll):
        return -np.inf

    return float(ll)

def implied_covariance_from_B_Omega(B, Omega):
    """
    For row-vector convention E = X(I-B):
      Cov(X) = (I-B)^(-T) Omega (I-B)^(-1)
    """
    B = np.asarray(B, dtype=np.float64)
    Omega = np.asarray(Omega, dtype=np.float64)

    d = B.shape[0]
    I = np.eye(d)
    ImB_inv = np.linalg.inv(I - B)

    Sigma = ImB_inv.T @ Omega @ ImB_inv
    Sigma = 0.5 * (Sigma + Sigma.T)

    return Sigma

# ============================================================
# 5. RICF-BIC score for fixed graph
# ============================================================

def score_bap_ricf(
    X,
    graph,
    *,
    ricf_max_iter=100,
    ricf_tol=1e-6,
    ridge=1e-10,
    min_var=1e-8,
    jitter=1e-10,
    penalty_coef=1.0,
    include_node_penalty=True,
    verbose=False,
):
    """
    Fit fixed BAP graph by RICF, then compute Nowzohour-style score:

      s(G) = 1/n * ( max_lik - penalty_coef * (d + #edges) log n )

    If include_node_penalty=False:
      s(G) = 1/n * ( max_lik - penalty_coef * #edges log n )

    The original paper includes d + #edges.
    """
    graph.validate()

    X = np.asarray(X, dtype=np.float64)
    X = center_data_np(X)
    n, d = X.shape

    fit = fit_bap_ricf(
        X,
        graph,
        max_iter=ricf_max_iter,
        tol=ricf_tol,
        ridge=ridge,
        min_var=min_var,
        jitter=jitter,
        verbose=verbose,
    )

    B_hat = fit["B"]
    Omega_hat = fit["Omega"]

    ll = gaussian_sem_loglik_from_B_Omega(
        X,
        B_hat,
        Omega_hat,
        center=False,
        jitter=jitter,
    )

    num_edges = graph.num_edges()

    if include_node_penalty:
        num_params_penalty = d + num_edges
    else:
        num_params_penalty = num_edges

    score = (ll - penalty_coef * num_params_penalty * math.log(n)) / n

    Sigma_hat = implied_covariance_from_B_Omega(B_hat, Omega_hat)

    return {
        "graph": graph,
        "score": float(score),
        "loglik": float(ll),
        "B": B_hat,
        "Omega": Omega_hat,
        "Sigma": Sigma_hat,
        "num_edges": int(num_edges),
        "num_params_penalty": int(num_params_penalty),
        "ricf_converged": bool(fit["converged"]),
        "ricf_n_iter": int(fit["n_iter"]),
        "ricf_max_change": float(fit["max_change"]),
    }

# ============================================================
# 6. RICF score greedy hill climbing
# ============================================================

def greedy_hill_climb_bap_ricf(
    X,
    init_graph,
    *,
    ricf_max_iter=100,
    ricf_tol=1e-6,
    ridge=1e-10,
    min_var=1e-8,
    jitter=1e-10,
    penalty_coef=1.0,
    include_node_penalty=True,
    improvement_tol=1e-8,
    max_hill_steps=None,
    verbose=True,
):
    """
    Greedy hill climbing over BAP local neighborhood using RICF-BIC score.
    """
    init_graph.validate()

    X = np.asarray(X, dtype=np.float64)
    X = center_data_np(X)

    current = init_graph.copy()

    current_fit = score_bap_ricf(
        X,
        current,
        ricf_max_iter=ricf_max_iter,
        ricf_tol=ricf_tol,
        ridge=ridge,
        min_var=min_var,
        jitter=jitter,
        penalty_coef=penalty_coef,
        include_node_penalty=include_node_penalty,
        verbose=False,
    )

    current_score = current_fit["score"]

    if verbose:
        print(
            f"[RICF-hill] start score={current_score:.6f}, "
            f"edges={current.num_edges()}, "
            f"ll={current_fit['loglik']:.3f}"
        )

    history = [{
        "graph": current.copy(),
        "score": current_score,
        "fit": current_fit,
    }]

    step = 0

    while True:
        if max_hill_steps is not None and step >= max_hill_steps:
            if verbose:
                print(f"[RICF-hill] reached max_hill_steps={max_hill_steps}")
            break

        neighbors = all_local_neighbors(current)

        if verbose:
            print(
                f"[RICF-hill] step={step}, "
                f"current_score={current_score:.6f}, "
                f"num_neighbors={len(neighbors)}"
            )

        best_neighbor = None
        best_neighbor_fit = None
        best_neighbor_score = current_score

        for k, H in enumerate(neighbors):
            fit_H = score_bap_ricf(
                X,
                H,
                ricf_max_iter=ricf_max_iter,
                ricf_tol=ricf_tol,
                ridge=ridge,
                min_var=min_var,
                jitter=jitter,
                penalty_coef=penalty_coef,
                include_node_penalty=include_node_penalty,
                verbose=False,
            )

            score_H = fit_H["score"]

            if score_H > best_neighbor_score + improvement_tol:
                best_neighbor = H
                best_neighbor_fit = fit_H
                best_neighbor_score = score_H

        if best_neighbor is None:
            if verbose:
                print(
                    f"[RICF-hill] stop at local optimum, "
                    f"score={current_score:.6f}, edges={current.num_edges()}"
                )
            break

        current = best_neighbor
        current_score = best_neighbor_score

        history.append({
            "graph": current.copy(),
            "score": current_score,
            "fit": best_neighbor_fit,
        })

        if verbose:
            print(
                f"[RICF-hill] move: "
                f"score={current_score:.6f}, "
                f"edges={current.num_edges()}, "
                f"ll={best_neighbor_fit['loglik']:.3f}, "
                f"ricf_iter={best_neighbor_fit['ricf_n_iter']}, "
                f"converged={best_neighbor_fit['ricf_converged']}"
            )

        step += 1

    best_fit = history[-1]["fit"]

    return {
        "best_graph": current,
        "best_score": current_score,
        "best_fit": best_fit,
        "history": history,
    }

# ============================================================
# 7. RICF score random restarts
# ============================================================

def bap_greedy_search_ricf(
    X,
    *,
    n_restarts=20,
    include_empty_start=True,
    restart_burnin=500,
    seed=None,
    ricf_max_iter=100,
    ricf_tol=1e-6,
    ridge=1e-10,
    min_var=1e-8,
    jitter=1e-10,
    penalty_coef=1.0,
    include_node_penalty=True,
    improvement_tol=1e-8,
    max_hill_steps=None,
    verbose=True,
):
    """
    Full BAP greedy score-based search using RICF score.

    This is the Nowzohour-style discrete search:
      - random restarts
      - greedy hill climbing
      - fixed-graph RICF MLE
      - BIC-like score

    No tanh penalty.
    No augmented Lagrangian.
    """
    X = np.asarray(X, dtype=np.float64)
    X = center_data_np(X)
    n, d = X.shape

    if seed is not None:
        np.random.seed(seed)
        random.seed(seed)

    restart_graphs = []

    if include_empty_start:
        restart_graphs.append(empty_bap(d))

    for r in range(n_restarts):
        g0 = random_bap_mcmc(
            d=d,
            burnin=restart_burnin,
            seed=None if seed is None else seed + 10000 + r,
            start_graph=None,
        )
        restart_graphs.append(g0)

    all_runs = []

    global_best_score = -np.inf
    global_best_graph = None
    global_best_run = None

    for r, g0 in enumerate(restart_graphs):
        if verbose:
            print("=" * 90)
            print(
                f"[RICF-restart {r + 1}/{len(restart_graphs)}] "
                f"initial edges={g0.num_edges()}"
            )

        run = greedy_hill_climb_bap_ricf(
            X,
            g0,
            ricf_max_iter=ricf_max_iter,
            ricf_tol=ricf_tol,
            ridge=ridge,
            min_var=min_var,
            jitter=jitter,
            penalty_coef=penalty_coef,
            include_node_penalty=include_node_penalty,
            improvement_tol=improvement_tol,
            max_hill_steps=max_hill_steps,
            verbose=verbose,
        )

        all_runs.append(run)

        if run["best_score"] > global_best_score:
            global_best_score = run["best_score"]
            global_best_graph = run["best_graph"].copy()
            global_best_run = run

        if verbose:
            print(
                f"[RICF-restart {r + 1}] local best score={run['best_score']:.6f}, "
                f"edges={run['best_graph'].num_edges()}"
            )

    return {
        "best_graph": global_best_graph,
        "best_score": float(global_best_score),
        "best_run": global_best_run,
        "best_fit": global_best_run["best_fit"] if global_best_run is not None else None,
        "all_runs": all_runs,
    }

import math
import random
import numpy as np
import torch

# ============================================================
# 0. 如果你之前的搜索函数名是 bap_greedy_search_with_random_restarts，
#    这里包一层别名，方便直接调用 bap_greedy_search(...)
# ============================================================
def bap_greedy_search(X, seed=None, dtype=None, device=None, **search_kwargs):
    if hasattr(X, "detach"):
        X_np = X.detach().cpu().numpy()
    else:
        X_np = np.asarray(X, dtype=np.float64)

    return bap_greedy_search_ricf(
        X_np,
        seed=seed,
        **search_kwargs
    )

# ============================================================
# 1. 从 BAP 参数 (S, C, B_true, Omega_true) 生成数据
# ============================================================

def simulate_linear_gaussian_bap_data(B_true, Omega_true, n, seed=None, dtype=torch.float64):
    """
    根据线性高斯 BAP/ADMG SEM 生成数据。

    约定：
      B_true[i,j] 表示 i -> j 的系数
      X = E (I - B)^(-1),   E ~ N(0, Omega_true)

    因此协方差为
      Cov(X) = (I - B)^(-T) Omega_true (I - B)^(-1)

    注意：
    这和前面搜索代码里的 log_likelihood 保持一致，因为那里用了
      R = X (I - B)
    即 E = X (I - B)
    """
    if seed is not None:
        np.random.seed(seed)
        random.seed(seed)
        torch.manual_seed(seed)

    B_true = np.asarray(B_true, dtype=np.float64)
    Omega_true = np.asarray(Omega_true, dtype=np.float64)

    d = B_true.shape[0]
    I = np.eye(d, dtype=np.float64)

    ImB = I - B_true
    ImB_inv = np.linalg.inv(ImB)

    # Cov(X) = (I-B)^(-T) Omega (I-B)^(-1)
    Sigma_x = ImB_inv.T @ Omega_true @ ImB_inv

    X = np.random.multivariate_normal(
        mean=np.zeros(d, dtype=np.float64),
        cov=Sigma_x,
        size=n
    )

    return torch.tensor(X, dtype=dtype), Sigma_x

# ============================================================
# 2. 从搜索结果提取估计图的 S, C
# ============================================================

def graph_to_SC(graph):
    """
    将前面定义的 BAPGraph 转成 S, C 矩阵。
    这里约定：
      graph.D[i,j] = 1 表示 i -> j
      graph.C[i,j] = 1 表示 i <-> j
    """
    S_est = np.asarray(graph.D).astype(int)
    C_est = np.asarray(graph.C).astype(int)
    return S_est, C_est

# ============================================================
# 3. 友好的打印函数
# ============================================================

def format_matrix(M, name=None):
    M = np.asarray(M)
    s = np.array2string(M, separator=", ")
    if name is None:
        return s
    return f"{name} =\n{s}"

def print_pag_object(pag, name="PAG"):
    """
    尝试更友好地打印 pag；如果 pag 类自己定义了 __str__，
    直接 print(pag) 即可。
    """
    print(f"{name}:")
    print(pag)

# ============================================================
# 4. 单次实验：生成 GT -> 生成数据 -> BAP 搜索 -> 转 PAG -> 计算指标
# ============================================================

def run_one_experiment(
    exp_id,
    *,
    d,
    n,
    p_dir,
    p_bidir,
    gt_seed=None,
    data_seed=None,
    search_seed=None,
    gt_kwargs=None,
    search_kwargs=None,
    device="cpu",
    dtype=torch.float64,
):
    """
    单次实验流程：
      1) 生成 ground truth
      2) 根据 ground truth 参数生成数据
      3) 用 bap_greedy_search 估计图
      4) GT / estimate 转 PAG
      5) 计算 SHD 等指标
      6) 打印结果
    """
    if gt_kwargs is None:
        gt_kwargs = {}
    if search_kwargs is None:
        search_kwargs = {}

    # ---------------------------
    # (1) 生成 GT
    # ---------------------------
    gt = generate_random_ground_truth_er(
        d=d,
        p_dir=p_dir,
        p_bidir=p_bidir,
        seed=gt_seed,
        **gt_kwargs
    )

    S_true = np.asarray(gt["S_true"]).astype(int)
    C_true = np.asarray(gt["C_true"]).astype(int)
    B_true = np.asarray(gt["B_true"], dtype=np.float64)
    Omega_true = np.asarray(gt["Omega_true"], dtype=np.float64)

    # ---------------------------
    # (2) 生成数据
    # ---------------------------
    X, Sigma_x = simulate_linear_gaussian_bap_data(
        B_true=B_true,
        Omega_true=Omega_true,
        n=n,
        seed=data_seed,
        dtype=dtype,
    )
    X = X.to(device)

    # ---------------------------
    # (3) BAP 搜索估计
    # ---------------------------
    est_result = bap_greedy_search(
        X,
        seed=search_seed,
        dtype=dtype,
        device=device,
        **search_kwargs
    )

    est_graph = est_result["best_graph"]
    best_score = est_result["best_score"]

    S_est, C_est = graph_to_SC(est_graph)

    # ---------------------------
    # (4) GT / EST 转 PAG
    # 这里按你的函数签名来：
    # admg_to_pag(p, B_mat=None, Sigma_mat=None)
    #
    # 其中：
    #   B_mat   <- S (directed adjacency)
    #   Sigma_mat <- C (bidirected adjacency)
    # ---------------------------
    true_pag = admg_to_pag(p=d, B_mat=S_true, Sigma_mat=C_true)
    est_pag = admg_to_pag(p=d, B_mat=S_est, Sigma_mat=C_est)

    # ---------------------------
    # (5) PAG 指标
    # ---------------------------
    metrics = compute_pag_metrics(true_pag, est_pag)

    # ---------------------------
    # (6) 打印
    # ---------------------------
    print("\n" + "=" * 100)
    print(f"Experiment {exp_id}")
    print("-" * 100)

    print(format_matrix(S_true, "GT S_true"))
    print(format_matrix(C_true, "GT C_true"))
    print()

    print(format_matrix(S_est, "EST S_est"))
    print(format_matrix(C_est, "EST C_est"))
    print()

    print_pag_object(true_pag, name="GT PAG")
    print()
    print_pag_object(est_pag, name="EST PAG")
    print()

    print(f"Best search score = {best_score:.6f}")
    print(f"Metrics = {metrics}")
    print(f"SHD = {metrics['shd']}")

    return {
        "exp_id": exp_id,
        "gt": gt,
        "X": X.detach().cpu().numpy(),
        "Sigma_x": Sigma_x,
        "est_result": est_result,
        "S_true": S_true,
        "C_true": C_true,
        "S_est": S_est,
        "C_est": C_est,
        "true_pag": true_pag,
        "est_pag": est_pag,
        "metrics": metrics,
    }

# ============================================================
# 5. 多次实验并汇总平均 SHD
# ============================================================

def run_bap_pag_benchmark(
    *,
    n_experiments=10,
    d=5,
    n=500,
    p_dir=0.2,
    p_bidir=0.1,
    gt_seed_base=1000,
    data_seed_base=2000,
    search_seed_base=3000,
    gt_kwargs=None,
    search_kwargs=None,
    device="cpu",
    dtype=torch.float64,
):
    """
    多次实验：
      - 每次生成一个新的 GT
      - 生成数据
      - BAP 搜索
      - 转 PAG
      - 计算 SHD
      - 最后输出平均 SHD
    """
    if gt_kwargs is None:
        gt_kwargs = {}
    if search_kwargs is None:
        search_kwargs = {}

    all_results = []
    shd_list = []

    for t in range(n_experiments):
        result_t = run_one_experiment(
            exp_id=t + 1,
            d=d,
            n=n,
            p_dir=p_dir,
            p_bidir=p_bidir,
            gt_seed=gt_seed_base + t if gt_seed_base is not None else None,
            data_seed=data_seed_base + t if data_seed_base is not None else None,
            search_seed=search_seed_base + t if search_seed_base is not None else None,
            gt_kwargs=gt_kwargs,
            search_kwargs=search_kwargs,
            device=device,
            dtype=dtype,
        )

        all_results.append(result_t)
        shd_list.append(float(result_t["metrics"]["shd"]))

    mean_shd = float(np.mean(shd_list)) if len(shd_list) > 0 else float("nan")
    std_shd = float(np.std(shd_list)) if len(shd_list) > 0 else float("nan")

    print("\n" + "#" * 100)
    print("Summary over all experiments")
    print("#" * 100)
    print(f"Number of experiments = {n_experiments}")
    print(f"SHD list = {shd_list}")
    print(f"Average SHD = {mean_shd:.6f}")
    print(f"Std SHD = {std_shd:.6f}")

    return {
        "all_results": all_results,
        "shd_list": shd_list,
        "mean_shd": mean_shd,
        "std_shd": std_shd,
    }

# ============================================================
# 6. 使用示例
# ============================================================

if __name__ == "__main__":
    ricf_search_kwargs = dict(
        n_restarts=0,
        include_empty_start=True,
        restart_burnin=300,

        ricf_max_iter=100,
        ricf_tol=1e-6,
        ridge=1e-10,
        min_var=1e-8,
        jitter=1e-10,

        penalty_coef=1.0,
        include_node_penalty=True,

        improvement_tol=1e-8,
        max_hill_steps=None,
        verbose=True,
        )

    gt_kwargs = dict(
        B_abs_low=0.3,
        B_abs_high=1.5,
        Omega_diag_low=1.0,
        Omega_diag_high=2.0,
        Omega_off_abs_low=0.1,
        Omega_off_abs_high=0.6,
        B_allow_negative=True,
        Omega_allow_negative=True,
        spd_floor=1e-3,
    )

    summary = run_bap_pag_benchmark(
        n_experiments=10,
        d=8,
        n=1000,
        p_dir=0.40,
        p_bidir=0.20,
        gt_seed_base=2026,
        data_seed_base=2027,
        search_seed_base=2028,
        gt_kwargs=gt_kwargs,
        search_kwargs=ricf_search_kwargs,
        device="cpu",
        dtype=torch.float64,
    )