# -*- coding: utf-8 -*-
"""wbic_advi_L1/gumbel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RxpZrjyNoT8NGpX5HlI-MfatO2rOf2yo
"""

import math
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
#!pip install python-igraph
#!pip install causal-learn
import igraph as ig
from causallearn.graph.Dag import Dag
from causallearn.graph.GraphNode import GraphNode
from causallearn.utils.DAG2PAG import dag2pag
from causallearn.graph.Endpoint import Endpoint

# ============================================================
# Ground-truth generation by ER graphs
# ============================================================

def _graph_to_adjmat(G):
    return np.array(G.get_adjacency().data, dtype=np.float64)

def simulate_er_dag_igraph(d: int, p_edge: float, rng=None):
    """
    用 igraph 生成 ER 无向图，再随机赋予一个拓扑顺序，定向成 DAG。
    约定: S[i,j]=1 表示 i -> j
    """
    if rng is None:
        rng = np.random.default_rng()

    p_edge = float(np.clip(p_edge, 0.0, 1.0))
    G_und = ig.Graph.Erdos_Renyi(n=d, p=p_edge, directed=False, loops=False)
    A_und = _graph_to_adjmat(G_und)

    perm = rng.permutation(d)
    pos = np.empty(d, dtype=int)
    pos[perm] = np.arange(d)

    S = np.zeros((d, d), dtype=np.float64)
    for i in range(d):
        for j in range(i + 1, d):
            if A_und[i, j] != 0:
                if pos[i] < pos[j]:
                    S[i, j] = 1.0
                else:
                    S[j, i] = 1.0
    return S

def simulate_er_bidirected_igraph(d: int, p_edge: float, rng=None):
    """
    用 igraph 生成无向 ER 图作为 bidirected 结构。
    返回对称 0/1 矩阵 C，且对角线为 1。
    """
    if rng is None:
        rng = np.random.default_rng()

    p_edge = float(np.clip(p_edge, 0.0, 1.0))
    G = ig.Graph.Erdos_Renyi(n=d, p=p_edge, directed=False, loops=False)
    A = _graph_to_adjmat(G)

    C = ((A + A.T) > 0).astype(np.float64)
    np.fill_diagonal(C, 1.0)
    return C

def sample_weighted_B_from_S(
    S,
    rng=None,
    abs_low=0.3,
    abs_high=1.5,
    allow_negative=True,
):
    """
    根据 0/1 结构矩阵 S 生成 weighted B_true.
    约定: B[i,j] 表示 i -> j
    """
    if rng is None:
        rng = np.random.default_rng()

    d = S.shape[0]
    B = np.zeros((d, d), dtype=np.float64)

    rows, cols = np.where(S != 0)
    for i, j in zip(rows, cols):
        mag = rng.uniform(abs_low, abs_high)
        sign = rng.choice([-1.0, 1.0]) if allow_negative else 1.0
        B[i, j] = sign * mag

    return B

def sample_weighted_Omega_from_C(
    C,
    rng=None,
    diag_low=1.0,
    diag_high=2.0,
    off_abs_low=0.1,
    off_abs_high=0.6,
    allow_negative=True,
    spd_floor=1e-3,
):
    """
    根据 0/1 结构矩阵 C 生成 weighted Omega_true.
    - 对角线随机正值
    - C[i,j]=1 的非对角位置给随机权重
    - 最后通过最小特征值修正保证正定:
          Omega <- Omega + soft_shift * I
      这里直接用线性 shift:
          shift = max(0, spd_floor - lambda_min)
    """
    if rng is None:
        rng = np.random.default_rng()

    d = C.shape[0]
    Omega = np.zeros((d, d), dtype=np.float64)

    diag_vals = rng.uniform(diag_low, diag_high, size=d)
    np.fill_diagonal(Omega, diag_vals)

    for i in range(d):
        for j in range(i + 1, d):
            if C[i, j] != 0:
                mag = rng.uniform(off_abs_low, off_abs_high)
                sign = rng.choice([-1.0, 1.0]) if allow_negative else 1.0
                val = sign * mag
                Omega[i, j] = val
                Omega[j, i] = val

    eigvals = np.linalg.eigvalsh(Omega)
    lam_min = eigvals.min()
    shift = max(0.0, spd_floor - lam_min)
    if shift > 0:
        Omega = Omega + shift * np.eye(d, dtype=np.float64)

    return Omega

def generate_random_ground_truth_er(
    d,
    p_dir,
    p_bidir,
    seed=None,
    B_abs_low=0.3,
    B_abs_high=1.5,
    Omega_diag_low=1.0,
    Omega_diag_high=2.0,
    Omega_off_abs_low=0.1,
    Omega_off_abs_high=0.6,
    B_allow_negative=True,
    Omega_allow_negative=True,
    spd_floor=1e-3,
):
    """
    一次性生成:
      - S_true: ER DAG 结构
      - C_true: ER bidirected 结构
      - B_true: 根据 S_true 加权
      - Omega_true: 根据 C_true 加权并修正为 SPD
    """
    rng = np.random.default_rng(seed)

    S_true = simulate_er_dag_igraph(d=d, p_edge=p_dir, rng=rng)
    C_true = simulate_er_bidirected_igraph(d=d, p_edge=p_bidir, rng=rng)

    B_true = sample_weighted_B_from_S(
        S_true,
        rng=rng,
        abs_low=B_abs_low,
        abs_high=B_abs_high,
        allow_negative=B_allow_negative,
    )

    Omega_true = sample_weighted_Omega_from_C(
        C_true,
        rng=rng,
        diag_low=Omega_diag_low,
        diag_high=Omega_diag_high,
        off_abs_low=Omega_off_abs_low,
        off_abs_high=Omega_off_abs_high,
        allow_negative=Omega_allow_negative,
        spd_floor=spd_floor,
    )

    return {
        "d": d,
        "S_true": S_true,
        "C_true": C_true,
        "B_true": B_true,
        "Omega_true": Omega_true,
    }


# ============================================================
# 0. Fixed convention
# ============================================================
# S[i,j] = 1 means i -> j
# B[i,j] != 0 means i -> j
# fixed topological order: only i < j directed edges are allowed


# ============================================================
# 2. Data simulation
# ============================================================

def simulate_linear_scm_i_to_j(n, B, Omega, seed=42):
    """
    X = E (I - B)^(-1), where B[i,j] means i -> j.
    """
    rng = np.random.default_rng(seed)
    p = B.shape[0]
    L = np.linalg.cholesky(Omega)
    E = rng.standard_normal((n, p)) @ L.T
    X = E @ np.linalg.inv(np.eye(p) - B)
    return X


# ============================================================
# 3. SHD
# ============================================================

def admg_to_pag(p, edges=None, biedges=None, B_mat=None, Sigma_mat=None):
    """
    将 ADMG 转换为 PAG
    参数:
    - p: 观测变量的数量 (int)
    - edges: 有向边列表, 如 [(0, 2)]
    - biedges: 双向边列表, 如 [(0, 1), (1, 2)]
    - B_mat: 有向边权重矩阵 (可选)
    - Sigma_mat: 噪声协方差矩阵 (可选)
    """

    # 1. 初始化观测变量节点
    nodes = [GraphNode(str(i)) for i in range(p)]
    all_nodes = list(nodes)
    latent_nodes = []

    # 2. 创建一个空的 DAG 对象
    # 注意：dag2pag 需要输入一个包含显变量和隐变量的完整 DAG
    dag = Dag(all_nodes)

    # 3. 处理有向边 (Directed Edges)
    if B_mat is not None:
        # 从矩阵提取有向边 (B_ij 表示 i -> j)
        for i in range(p):
            for j in range(p):
                if B_mat[i, j] != 0:
                    dag.add_directed_edge(nodes[i], nodes[j])
    elif edges is not None:
        for i, j in edges:
            dag.add_directed_edge(nodes[i], nodes[j])

    # 4. 处理双向边 (Bidirected Edges) -> 转换为隐变量结构
    # 每条双向边 i <-> j 变成 L -> i 和 L -> j
    if Sigma_mat is not None:
        # 从矩阵提取双向边 (只看上三角，排除对角线)
        for i in range(p):
            for j in range(i + 1, p):
                if Sigma_mat[i, j] != 0:
                    # 创建新的隐变量节点
                    l_node = GraphNode(f"L_{i}_{j}")
                    dag.add_node(l_node)
                    latent_nodes.append(l_node)
                    # 添加从隐变量到两个观测点的有向边
                    dag.add_directed_edge(l_node, nodes[i])
                    dag.add_directed_edge(l_node, nodes[j])
    elif biedges is not None:
        for i, j in biedges:
            l_node = GraphNode(f"L_{i}_{j}")
            dag.add_node(l_node)
            latent_nodes.append(l_node)
            dag.add_directed_edge(l_node, nodes[i])
            dag.add_directed_edge(l_node, nodes[j])

    # 5. 调用 causal-learn 函数将 DAG 转为 PAG
    # 第二个参数是需要 marginalize 掉的隐变量列表
    pag = dag2pag(dag, latent_nodes)

    return pag

def compute_pag_metrics(true_pag, est_pag):
    """
    计算 SHD, Skeleton F1, Arrowhead F1
    基于 causal-learn 的 GeneralGraph 对象
    """
    # 获取邻接矩阵 (graph property stores the matrix)
    # causal-learn 矩阵定义: M[i, j] 表示 i 和 j 之间在 j 端点的类型
    # 0: No Edge, 1: Circle, 2: Arrow, 3: Tail

    true_adj = true_pag.graph
    est_adj = est_pag.graph
    p = true_adj.shape[0]

    # --- 1. Skeleton F1 ---
    # 只需要看是否有边 (非0)，只遍历上三角避免重复
    tp_skel = 0
    fp_skel = 0
    fn_skel = 0

    for i in range(p):
        for j in range(i + 1, p):
            has_edge_true = (true_adj[i, j] != 0)
            has_edge_est = (est_adj[i, j] != 0)

            if has_edge_true and has_edge_est:
                tp_skel += 1
            elif not has_edge_true and has_edge_est:
                fp_skel += 1
            elif has_edge_true and not has_edge_est:
                fn_skel += 1

    precision_skel = tp_skel / (tp_skel + fp_skel) if (tp_skel + fp_skel) > 0 else 0
    recall_skel = tp_skel / (tp_skel + fn_skel) if (tp_skel + fn_skel) > 0 else 0
    f1_skel = 2 * precision_skel * recall_skel / (precision_skel + recall_skel) if (precision_skel + recall_skel) > 0 else 0

    # --- 2. Arrowhead F1 ---
    # 统计所有箭头 (Arrow = 2) 的预测情况
    # 遍历整个矩阵 (包括 i,j 和 j,i)，因为箭头是有方向的
    tp_arrow = 0
    fp_arrow = 0
    fn_arrow = 0

    # ARROW 在 causal-learn Endpoint 中通常对应值 2
    ARROW_MARK = Endpoint.ARROW.value

    for i in range(p):
        for j in range(p):
            if i == j: continue

            # True PAG 在 j 处是否有箭头
            is_arrow_true = (true_adj[i, j] == ARROW_MARK)
            # Est PAG 在 j 处是否有箭头
            is_arrow_est = (est_adj[i, j] == ARROW_MARK)

            if is_arrow_true and is_arrow_est:
                tp_arrow += 1
            elif not is_arrow_true and is_arrow_est:
                fp_arrow += 1
            elif is_arrow_true and not is_arrow_est:
                fn_arrow += 1

    precision_arrow = tp_arrow / (tp_arrow + fp_arrow) if (tp_arrow + fp_arrow) > 0 else 0
    recall_arrow = tp_arrow / (tp_arrow + fn_arrow) if (tp_arrow + fn_arrow) > 0 else 0
    f1_arrow = 2 * precision_arrow * recall_arrow / (precision_arrow + recall_arrow) if (precision_arrow + recall_arrow) > 0 else 0

    # --- 3. SHD (Structural Hamming Distance) ---
    # 定义：增加/删除边 + 修改端点方向的操作总数
    # 策略：
    # - 边存在性不同: SHD + 1.5
    # - 边存在且相同: 检查两个端点，每个端点不同 SHD + 0.5 (累计为1)

    shd = 0
    for i in range(p):
        for j in range(i + 1, p):
          diff = (true_adj[i, j] != est_adj[i, j]) or (true_adj[j, i] != est_adj[j, i])
          if diff: shd+=1
            #has_edge_true = (true_adj[i, j] != 0)
            #has_edge_est = (est_adj[i, j] != 0)

            #if has_edge_true != has_edge_est:
                # 骨架错误 (多边或少边)
                #shd += 1.5
            #elif has_edge_true and has_edge_est:
                # 骨架正确，检查方向 (两个端点)
                # 检查 i 端的标记
            #    if true_adj[j, i] != est_adj[j, i]:
            #        shd += 0.5
                # 检查 j 端的标记
            #    if true_adj[i, j] != est_adj[i, j]:
            #        shd += 0.5

    return {
        "shd": int(shd) if shd.is_integer() else shd,
        "f1_skeleton": round(f1_skel, 4),
        "f1_arrowhead": round(f1_arrow, 4),
        "precision_arrow": round(precision_arrow, 4),
        "recall_arrow": round(recall_arrow, 4)
    }


def dag_shd(S1, S2):
    A = (S1 != 0).to(torch.int64)
    B = (S2 != 0).to(torch.int64)
    p = A.shape[0]

    shd = 0
    for i in range(p):
        for j in range(i + 1, p):
            a_ij, a_ji = int(A[i, j]), int(A[j, i])
            b_ij, b_ji = int(B[i, j]), int(B[j, i])

            state_a = (a_ij, a_ji)
            state_b = (b_ij, b_ji)

            if state_a == state_b:
                continue
            elif state_a in [(1, 0), (0, 1)] and state_b in [(1, 0), (0, 1)]:
                shd += 1
            else:
                shd += 1
    return shd


def se_shd(C1, C2):
    A = (C1 != 0).to(torch.int64)
    B = (C2 != 0).to(torch.int64)
    p = A.shape[0]

    shd = 0
    for i in range(p):
        for j in range(i + 1, p):
            if int(A[i, j]) != int(B[i, j]):
                shd += 1
    return shd


def total_shd(S_hat, C_hat, S_true, C_true):
    shd_b = dag_shd(S_hat, S_true)
    shd_c = se_shd(C_hat, C_true)
    return {
        "shd_B": shd_b,
        "shd_C": shd_c,
        "shd_total": shd_b + shd_c,
    }


# ============================================================
# 4. Continuous ADMG search with original parameterization
# ============================================================

class ContinuousADMGSearchOriginalParam(nn.Module):
    """
    Original-style parameterization:

      B_eff[i,j] = S[i,j] * zeta_B[i,j],  i < j

      L_ii = exp(zeta_D[i])
      L_ij = C[i,j] * zeta_L[i,j],        i > j
      Omega = L L^T

    Structure:
      S[i,j] = sigmoid(A_logits[i,j]) for i < j
      C[i,j] = sigmoid(U_logits[i,j]) for i < j, symmetric

    Convention:
      S[i,j], B[i,j] means i -> j.
    """

    def __init__(
        self,
        d,
        eps_sigma=1e-6,
        sigma_B_prior=2.0,
        dtype=torch.float64,
        device="cpu",
    ):
        super().__init__()

        self.d = d
        self.eps_sigma = eps_sigma
        self.sigma_B_prior = sigma_B_prior
        self.dtype = dtype
        self.device = device

        dir_mask = torch.ones(d, d, dtype=dtype, device=device) - torch.eye(d, dtype=dtype, device=device)
        c_upper_mask = torch.triu(torch.ones(d, d, dtype=dtype, device=device), diagonal=1)
        l_lower_mask = torch.tril(torch.ones(d, d, dtype=dtype, device=device), diagonal=-1)

        self.register_buffer("dir_mask", dir_mask)
        self.register_buffer("c_upper_mask", c_upper_mask)
        self.register_buffer("l_lower_mask", l_lower_mask)
        self.register_buffer("I", torch.eye(d, dtype=dtype, device=device))

        self.mu_B = nn.Parameter(torch.zeros(d, d, dtype=dtype, device=device))
        self.rho_B = nn.Parameter(torch.full((d, d), math.log(0.1), dtype=dtype, device=device))

        self.mu_L = nn.Parameter(torch.zeros(d, d, dtype=dtype, device=device))
        self.rho_L = nn.Parameter(torch.full((d, d), math.log(0.1), dtype=dtype, device=device))

        self.mu_D = nn.Parameter(torch.zeros(d, dtype=dtype, device=device))
        self.rho_D = nn.Parameter(torch.full((d,), math.log(0.1), dtype=dtype, device=device))

        self.A_logits = nn.Parameter(torch.zeros(d, d, dtype=dtype, device=device))
        self.U_logits = nn.Parameter(torch.zeros(d, d, dtype=dtype, device=device))

    def init_structure_logits(
        self,
        a_mean=0.0,
        a_std=0.1,
        u_mean=0.0,
        u_std=0.1,
        seed=None,
    ):
        if seed is not None:
            torch.manual_seed(seed)

        with torch.no_grad():
            self.A_logits.copy_(a_mean + a_std * torch.randn_like(self.A_logits))
            self.U_logits.copy_(u_mean + u_std * torch.randn_like(self.U_logits))

            self.A_logits.mul_(self.dir_mask)
            self.U_logits.mul_(self.c_upper_mask)

    def init_variational(self, seed=None):
        if seed is not None:
            torch.manual_seed(seed)

        with torch.no_grad():
            self.mu_B.copy_(0.01 * torch.randn_like(self.mu_B))
            self.mu_L.copy_(0.01 * torch.randn_like(self.mu_L))
            self.mu_D.copy_(0.01 * torch.randn_like(self.mu_D))

            self.rho_B.fill_(math.log(0.1))
            self.rho_L.fill_(math.log(0.1))
            self.rho_D.fill_(math.log(0.1))

            self.mu_B.mul_(self.dir_mask)
            self.mu_L.mul_(self.l_lower_mask)

    def sigma_from_rho(self, rho):
        return torch.exp(rho) + self.eps_sigma

    def soft_S(self):
        return torch.sigmoid(self.A_logits) * self.dir_mask

    def soft_C_upper(self):
        return torch.sigmoid(self.U_logits) * self.c_upper_mask

    def soft_C_full(self):
        Cup = self.soft_C_upper()
        return Cup + Cup.T + self.I

    def soft_C_lower(self):
        Cup = self.soft_C_upper()
        return Cup.T * self.l_lower_mask

    def sample_zeta(self, n_mc):
        sig_B = self.sigma_from_rho(self.rho_B)
        sig_L = self.sigma_from_rho(self.rho_L)
        sig_D = self.sigma_from_rho(self.rho_D)

        eps_B = torch.randn((n_mc, self.d, self.d), dtype=self.dtype, device=self.device)
        eps_L = torch.randn((n_mc, self.d, self.d), dtype=self.dtype, device=self.device)
        eps_D = torch.randn((n_mc, self.d), dtype=self.dtype, device=self.device)

        zeta_B = self.mu_B.unsqueeze(0) + sig_B.unsqueeze(0) * eps_B
        zeta_L = self.mu_L.unsqueeze(0) + sig_L.unsqueeze(0) * eps_L
        zeta_D = self.mu_D.unsqueeze(0) + sig_D.unsqueeze(0) * eps_D

        zeta_B = zeta_B * self.dir_mask
        zeta_L = zeta_L * self.l_lower_mask

        return zeta_B, zeta_L, zeta_D

    def build_B(self, zeta_B):
        """
        B_eff[i,j] = S[i,j] * zeta_B[i,j], i < j.
        """
        S = self.soft_S().unsqueeze(0)
        B = S * zeta_B
        return B

    def build_Omega_and_log_jac(self, zeta_L, zeta_D):
        """
        L_ii = exp(zeta_D_i)
        L_ij = C_ij * zeta_L_ij, i > j
        Omega = L L^T

        log_jac from diagonal exp transform:
          sum_i zeta_D_i
        """
        n_mc = zeta_D.shape[0]

        C_lower = self.soft_C_lower().unsqueeze(0)

        L = torch.zeros((n_mc, self.d, self.d), dtype=self.dtype, device=self.device)
        L = L + C_lower * zeta_L

        diag_vals = torch.exp(zeta_D)
        L = L + torch.diag_embed(diag_vals)

        Omega = L @ L.transpose(-1, -2)
        log_jac = zeta_D.sum(dim=1)

        return Omega, log_jac

    def log_likelihood(self, X, B, Omega):
        """
        X: [n,d]
        B: [mc,d,d], B[i,j] means i -> j
        Omega: [mc,d,d]

        X = E (I - B)^(-1)
        E = X (I - B)
        loglik = n log|det(I-B)| - 1/2 n log|Omega|
                 - 1/2 tr(E Omega^{-1} E^T)
                 - nd/2 log(2pi)

        For strictly upper-triangular B, log|det(I-B)| = 0,
        but computed explicitly for consistency.
        """
        n, p = X.shape
        mc = B.shape[0]

        ImB = self.I.unsqueeze(0) - B

        sign_imb, logdet_imb = torch.linalg.slogdet(ImB)
        sign_om, logdet_om = torch.linalg.slogdet(Omega)

        R = torch.matmul(X.unsqueeze(0), ImB)

        Omega_inv = torch.linalg.inv(Omega)
        quad = torch.einsum("mni,mij,mnj->m", R, Omega_inv, R)

        const = -0.5 * n * p * math.log(2.0 * math.pi)
        ll = n * logdet_imb - 0.5 * n * logdet_om - 0.5 * quad + const

        invalid = (sign_imb <= 0) | (sign_om <= 0) | (~torch.isfinite(ll))
        ll = torch.where(invalid, torch.full_like(ll, -1.0e30), ll)

        return ll

    def kl_terms(self):
        """
        Analytic KL:
          B prior: N(0, sigma_B_prior^2)
          L offdiag and D prior: N(0, 1)

        rho parameterization:
          sigma = exp(rho)
        """
        sig_B = self.sigma_from_rho(self.rho_B)
        sig_L = self.sigma_from_rho(self.rho_L)
        sig_D = self.sigma_from_rho(self.rho_D)

        sB2 = self.sigma_B_prior ** 2

        kl_B_mat = 0.5 * (
            sig_B**2 / sB2
            + self.mu_B**2 / sB2
            - 1.0
            - 2.0 * torch.log(sig_B)
            + math.log(sB2)
        )
        kl_B = (kl_B_mat * self.dir_mask).sum()

        kl_L_mat = 0.5 * (
            sig_L**2
            + self.mu_L**2
            - 1.0
            - 2.0 * torch.log(sig_L)
        )
        kl_L = (kl_L_mat * self.l_lower_mask).sum()

        kl_D_vec = 0.5 * (
            sig_D**2
            + self.mu_D**2
            - 1.0
            - 2.0 * torch.log(sig_D)
        )
        kl_D = kl_D_vec.sum()

        kl_Om = kl_L + kl_D
        kl_total = kl_B + kl_Om

        return kl_total, kl_B, kl_Om, kl_L, kl_D

    def objective(
        self,
        X,
        beta,
        n_mc=8,
        alpha_B=0.05,
        alpha_C=0.05,
        lambda_acyc = 1,
        include_log_jac=True,
    ):
        zeta_B, zeta_L, zeta_D = self.sample_zeta(n_mc=n_mc)

        B = self.build_B(zeta_B)
        Omega, log_jac = self.build_Omega_and_log_jac(zeta_L, zeta_D)

        ll = self.log_likelihood(X, B, Omega)

        if include_log_jac:
            mc_term = beta * ll + log_jac
        else:
            mc_term = beta * ll

        mc_mean = mc_term.mean()

        kl, kl_B, kl_Om, kl_L, kl_D = self.kl_terms()

        S_soft = self.soft_S()
        C_upper = self.soft_C_upper()

        l1_B = S_soft.sum()
        l1_C = C_upper.sum()
        h_acyc = torch.trace(torch.matrix_exp(S_soft * S_soft)) - self.d

        elbo = mc_mean - kl
        objective = elbo - alpha_B * l1_B - alpha_C * l1_C - lambda_acyc*h_acyc

        return {
            "objective": objective,
            "elbo": elbo,
            "mc_mean": mc_mean,
            "beta_ll_mean": (beta * ll).mean(),
            "ll_mean": ll.mean(),
            "log_jac_mean": log_jac.mean(),
            "kl": kl,
            "kl_B": kl_B,
            "kl_Om": kl_Om,
            "kl_L": kl_L,
            "kl_D": kl_D,
            "l1_B": l1_B,
            "l1_C": l1_C,
        }

    @torch.no_grad()
    def current_soft_graphs(self):
        S = self.soft_S().detach().cpu()
        C = self.soft_C_full().detach().cpu()
        return S, C

    @torch.no_grad()
    def threshold_graphs(self, tau_B=0.1, tau_C=0.1):
        S_soft = self.soft_S()
        C_up = self.soft_C_upper()
        S_bar = max(S_soft.mean(), tau_B)
        C_bar = max(torch.mean(C_up + C_up.T) / 2, tau_C)

        S_hat = (S_soft > S_bar).to(torch.float64)
        C_hat = (C_up > C_bar).to(torch.float64)
        C_hat = C_hat + C_hat.T + torch.eye(self.d, dtype=torch.float64, device=C_hat.device)

        return S_hat.detach().cpu(), C_hat.detach().cpu()


# ============================================================
# 5. Single optimization run
# ============================================================

def fit_continuous_search_original_param(
    X_np,
    n_steps=3000,
    lr=1e-2,
    n_mc=8,
    alpha_B=0.05,
    alpha_C=0.05,
    sigma_B_prior=2.0,
    init_a_mean=0.0,
    init_u_mean=0.0,
    init_std=0.1,
    tau_B=0.1,
    tau_C=0.1,
    lambda_acyc_init=1.0,    # 初始权重
    lambda_acyc_final=10000.0,  # 结束权重
    seed=123,
    device="cpu",
    verbose=True,
    include_log_jac=True,
    grad_clip=10.0,
):
    torch.manual_seed(seed)
    np.random.seed(seed)

    X = torch.tensor(X_np, dtype=torch.float64, device=device)
    n, d_local = X.shape
    beta = 1.0 / math.log(n)

    model = ContinuousADMGSearchOriginalParam(
        d=d_local,
        sigma_B_prior=sigma_B_prior,
        dtype=torch.float64,
        device=device,
    ).to(device=device, dtype=torch.float64)

    model.init_variational(seed=seed)
    model.init_structure_logits(
        a_mean=init_a_mean,
        a_std=init_std,
        u_mean=init_u_mean,
        u_std=init_std,
        seed=seed + 1,
    )

    optimizer = optim.Adam(model.parameters(), lr=lr)

    history = {
        "objective": [],
        "elbo": [],
        "mc_mean": [],
        "beta_ll_mean": [],
        "ll_mean": [],
        "log_jac_mean": [],
        "kl": [],
        "kl_B": [],
        "kl_Om": [],
        "kl_L": [],
        "kl_D": [],
        "l1_B": [],
        "l1_C": [],
    }

    for t in range(n_steps):
        # 指数增长计算当前步骤的权重
        curr_lambda = math.exp(math.log(lambda_acyc_init) + t * (math.log(lambda_acyc_final) - math.log(lambda_acyc_init)) / n_steps)
        optimizer.zero_grad()

        out = model.objective(
            X=X,
            beta=beta,
            n_mc=n_mc,
            alpha_B=alpha_B,
            alpha_C=alpha_C,
            lambda_acyc=curr_lambda,
            include_log_jac=include_log_jac,
        )

        loss = -out["objective"]
        loss.backward()

        if grad_clip is not None:
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=grad_clip)

        optimizer.step()

        for k in history:
            history[k].append(float(out[k].detach().cpu()))

        if verbose and (t == 0 or (t + 1) % 200 == 0):
            print(
                f"[step {t+1:5d}] "
                f"obj={history['objective'][-1]:12.4f} "
                f"elbo={history['elbo'][-1]:12.4f} "
                f"ll={history['ll_mean'][-1]:12.4f} "
                f"logJ={history['log_jac_mean'][-1]:9.4f} "
                f"kl={history['kl'][-1]:10.4f} "
                f"l1B={history['l1_B'][-1]:8.4f} "
                f"l1C={history['l1_C'][-1]:8.4f}"
            )

    S_soft, C_soft = model.current_soft_graphs()
    S_hat, C_hat = model.threshold_graphs(tau_B=tau_B, tau_C=tau_C)

    result = {
        "model": model,
        "history": history,
        "S_soft": S_soft.numpy(),
        "C_soft": C_soft.numpy(),
        "S_hat": S_hat.numpy(),
        "C_hat": C_hat.numpy(),
        "final_objective": history["objective"][-1],
        "final_elbo": history["elbo"][-1],
        "final_ll_mean": history["ll_mean"][-1],
        "final_kl": history["kl"][-1],
        "final_l1_B": history["l1_B"][-1],
        "final_l1_C": history["l1_C"][-1],
    }

    return result

# ============================================================
# 6. Multiple initializations
# ============================================================

def run_multi_init_experiment_original_param(
    gt,
    n_samples=1000,
    n_steps=3000,
    lr=1e-2,
    n_mc=8,
    alpha_B=0.05,
    alpha_C=0.05,
    sigma_B_prior=2.0,
    tau_B=0.1,
    tau_C=0.1,
    init_configs=None,
    seed_data=42,
    device="cpu",
    include_log_jac=True,
    verbose=True
):
    S_true = gt["S_true"]
    C_true = gt["C_true"]
    B_true = gt["B_true"]
    Omega_true = gt["Omega_true"]

    X_np = simulate_linear_scm_i_to_j(
        n=n_samples,
        B=B_true,
        Omega=Omega_true,
        seed=seed_data,
    )

    if init_configs is None:
        init_configs = [
            {"name": "sparse_sparse", "a_mean": -3.0, "u_mean": -3.0, "std": 0.1, "seed": 101},
            {"name": "sparse_mid",    "a_mean": -3.0, "u_mean":  0.0, "std": 0.1, "seed": 102},
            {"name": "mid_mid",       "a_mean":  0.0, "u_mean":  0.0, "std": 0.1, "seed": 103},
            {"name": "dense_mid",     "a_mean":  3.0, "u_mean":  0.0, "std": 0.1, "seed": 104},
            {"name": "dense_dense",   "a_mean":  3.0, "u_mean":  3.0, "std": 0.1, "seed": 105},
        ]

    all_results = []

    S_true_t = torch.tensor(S_true, dtype=torch.float64)
    C_true_t = torch.tensor(C_true, dtype=torch.float64)

    for cfg in init_configs:
        if verbose:
            print("\n" + "=" * 80)
            print(f"INIT: {cfg['name']}")
            print("=" * 80)

        res = fit_continuous_search_original_param(
            X_np=X_np,
            n_steps=n_steps,
            lr=lr,
            n_mc=n_mc,
            alpha_B=alpha_B,
            alpha_C=alpha_C,
            sigma_B_prior=sigma_B_prior,
            init_a_mean=cfg["a_mean"],
            init_u_mean=cfg["u_mean"],
            init_std=cfg["std"],
            tau_B=tau_B,
            tau_C=tau_C,
            seed=cfg["seed"],
            device=device,
            verbose=verbose,
            include_log_jac=include_log_jac,
        )

        S_hat_t = torch.tensor(res["S_hat"], dtype=torch.float64)
        C_hat_t = torch.tensor(res["C_hat"], dtype=torch.float64)
        d = S_true_t.shape[0]
        pag_true = admg_to_pag(d,B_mat=S_true,Sigma_mat=C_true)
        try:
          # 尝试生成 PAG，如果 S_hat 包含环，这里会触发 NetworkXError
          pag_hat = admg_to_pag(d, B_mat=res["S_hat"], Sigma_mat=res["C_hat"])
          shd_res = compute_pag_metrics(pag_true, pag_hat)
          shd = shd_res["shd"]

          all_results.append({
            "init_name": cfg["name"],
            "config": cfg,
            "result": res,
            "shd": shd,
          })
          if verbose:
            print("\nFinal metrics:")
            print(
                {
                    "objective": res["final_objective"],
                    "elbo": res["final_elbo"],
                    "ll_mean": res["final_ll_mean"],
                    "kl": res["final_kl"],
                    "l1_B": res["final_l1_B"],
                    "l1_C": res["final_l1_C"],
                }
                )
            print("\nPag True:")
            print(pag_true)
            print("\nPag Hat:")
            print(pag_hat)
            print("\nSHD:")
            print(shd)
        except Exception as e:
          # 捕获错误并跳过该次初始化结果，继续下一次实验
          print(f"[Warning] Skipping init {cfg['name']} due to non-acyclic graph: {e}")
          continue

    all_results = sorted(
        all_results,
        key=lambda z: z["result"]["final_objective"],
        reverse=True,
    )

    if verbose:
        print("\n" + "=" * 80)
        print("SUMMARY OVER INITIALIZATIONS")
        print("=" * 80)

        for k, rr in enumerate(all_results, 1):
            print(
                f"{k:2d}. {rr['init_name']:<15s} "
                f"obj={rr['result']['final_objective']:12.4f} "
                f"elbo={rr['result']['final_elbo']:12.4f} "
                f"ll={rr['result']['final_ll_mean']:12.4f} "
                f"kl={rr['result']['final_kl']:10.4f} "
                f"l1B={rr['result']['final_l1_B']:8.4f} "
                f"l1C={rr['result']['final_l1_C']:8.4f} "
                f"SHD={rr['shd']}"
            )

    return {
        "ground_truth": gt,
        "X": X_np,
        "all_results": all_results,
    }

# ============================================================
# 4. Continuous ADMG search with Gumbel-Sigmoid gates
# ============================================================

class ContinuousADMGSearchGumbel(nn.Module):
    """
    Original parameterization for model parameters:
      B_eff[i,j] = S[i,j] * zeta_B[i,j],  i < j
      L_ii = exp(zeta_D[i])
      L_ij = C_lower[i,j] * zeta_L[i,j], i > j
      Omega = L L^T

    Structure gates:
      S and C are generated by Binary Concrete / Gumbel-Sigmoid from logits A, U
      No L1 penalty
    """

    def __init__(
        self,
        d,
        eps_sigma=1e-6,
        sigma_B_prior=2.0,
        tau_gumbel=1.0,
        hard=False,
        dtype=torch.float64,
        device="cpu",
    ):
        super().__init__()

        self.d = d
        self.eps_sigma = eps_sigma
        self.sigma_B_prior = sigma_B_prior
        self.tau_gumbel = tau_gumbel
        self.hard = hard
        self.dtype = dtype
        self.device = device

        dir_mask = torch.ones(d, d, dtype=dtype, device=device) - torch.eye(d, dtype=dtype, device=device)
        c_upper_mask = torch.triu(torch.ones(d, d, dtype=dtype, device=device), diagonal=1)
        l_lower_mask = torch.tril(torch.ones(d, d, dtype=dtype, device=device), diagonal=-1)

        self.register_buffer("dir_mask", dir_mask)
        self.register_buffer("c_upper_mask", c_upper_mask)
        self.register_buffer("l_lower_mask", l_lower_mask)
        self.register_buffer("I", torch.eye(d, dtype=dtype, device=device))

        # variational params
        self.mu_B = nn.Parameter(torch.zeros(d, d, dtype=dtype, device=device))
        self.rho_B = nn.Parameter(torch.full((d, d), math.log(0.1), dtype=dtype, device=device))

        self.mu_L = nn.Parameter(torch.zeros(d, d, dtype=dtype, device=device))
        self.rho_L = nn.Parameter(torch.full((d, d), math.log(0.1), dtype=dtype, device=device))

        self.mu_D = nn.Parameter(torch.zeros(d, dtype=dtype, device=device))
        self.rho_D = nn.Parameter(torch.full((d,), math.log(0.1), dtype=dtype, device=device))

        # structure logits
        self.A_logits = nn.Parameter(torch.zeros(d, d, dtype=dtype, device=device))
        self.U_logits = nn.Parameter(torch.zeros(d, d, dtype=dtype, device=device))

    # --------------------------------------------------------
    # init
    # --------------------------------------------------------
    def init_structure_logits(
        self,
        a_mean=0.0,
        a_std=0.1,
        u_mean=0.0,
        u_std=0.1,
        seed=None,
    ):
        if seed is not None:
            torch.manual_seed(seed)

        with torch.no_grad():
            self.A_logits.copy_(a_mean + a_std * torch.randn_like(self.A_logits))
            self.U_logits.copy_(u_mean + u_std * torch.randn_like(self.U_logits))
            self.A_logits.mul_(self.dir_mask)
            self.U_logits.mul_(self.c_upper_mask)

    def init_variational(self, seed=None):
        if seed is not None:
            torch.manual_seed(seed)

        with torch.no_grad():
            self.mu_B.copy_(0.01 * torch.randn_like(self.mu_B))
            self.mu_L.copy_(0.01 * torch.randn_like(self.mu_L))
            self.mu_D.copy_(0.01 * torch.randn_like(self.mu_D))

            self.rho_B.fill_(math.log(0.1))
            self.rho_L.fill_(math.log(0.1))
            self.rho_D.fill_(math.log(0.1))

            self.mu_B.mul_(self.dir_mask)
            self.mu_L.mul_(self.l_lower_mask)

    # --------------------------------------------------------
    # helpers
    # --------------------------------------------------------
    def sigma_from_rho(self, rho):
        return torch.exp(rho) + self.eps_sigma

    def _sample_binary_concrete(self, logits, tau=None, hard=None):
        """
        Binary Concrete / Gumbel-Sigmoid sample:
          y = sigmoid((logits + g) / tau),   g ~ Logistic(0,1)
        hard=True uses straight-through thresholding.
        """
        if tau is None:
            tau = self.tau_gumbel
        if hard is None:
            hard = self.hard

        u = torch.rand_like(logits)
        eps = 1e-20
        g = torch.log(u + eps) - torch.log(1.0 - u + eps)
        y_soft = torch.sigmoid((logits + g) / tau)

        if not hard:
            return y_soft

        y_hard = (y_soft > 0.5).to(y_soft.dtype)
        y = y_hard.detach() - y_soft.detach() + y_soft
        return y

    def sample_soft_S(self):
        return self._sample_binary_concrete(self.A_logits) * self.dir_mask

    def sample_soft_C_upper(self):
        return self._sample_binary_concrete(self.U_logits) * self.c_upper_mask

    def deterministic_S(self):
        return torch.sigmoid(self.A_logits) * self.dir_mask

    def deterministic_C_upper(self):
        return torch.sigmoid(self.U_logits) * self.c_upper_mask

    def deterministic_C_full(self):
        Cup = self.deterministic_C_upper()
        return Cup + Cup.T + self.I

    def sample_C_lower(self):
        Cup = self.sample_soft_C_upper()
        return Cup.T * self.l_lower_mask, Cup

    def sample_zeta(self, n_mc):
        sig_B = self.sigma_from_rho(self.rho_B)
        sig_L = self.sigma_from_rho(self.rho_L)
        sig_D = self.sigma_from_rho(self.rho_D)

        eps_B = torch.randn((n_mc, self.d, self.d), dtype=self.dtype, device=self.device)
        eps_L = torch.randn((n_mc, self.d, self.d), dtype=self.dtype, device=self.device)
        eps_D = torch.randn((n_mc, self.d), dtype=self.dtype, device=self.device)

        zeta_B = self.mu_B.unsqueeze(0) + sig_B.unsqueeze(0) * eps_B
        zeta_L = self.mu_L.unsqueeze(0) + sig_L.unsqueeze(0) * eps_L
        zeta_D = self.mu_D.unsqueeze(0) + sig_D.unsqueeze(0) * eps_D

        zeta_B = zeta_B * self.dir_mask
        zeta_L = zeta_L * self.l_lower_mask

        return zeta_B, zeta_L, zeta_D

    # --------------------------------------------------------
    # model build
    # --------------------------------------------------------
    def build_B(self, zeta_B, S_soft):
        """
        B_eff[i,j] = S_soft[i,j] * zeta_B[i,j], i < j
        """
        return zeta_B * S_soft.unsqueeze(0)

    def build_Omega_and_log_jac(self, zeta_L, zeta_D, C_lower_soft):
        """
        L_ii = exp(zeta_D_i)
        L_ij = C_lower_soft[i,j] * zeta_L[i,j], i > j
        Omega = L L^T
        log_jac = sum_i zeta_D_i
        """
        n_mc = zeta_D.shape[0]

        L = torch.zeros((n_mc, self.d, self.d), dtype=self.dtype, device=self.device)
        L = L + C_lower_soft.unsqueeze(0) * zeta_L
        diag_vals = torch.exp(zeta_D)
        L = L + torch.diag_embed(diag_vals)

        Omega = L @ L.transpose(-1, -2)
        log_jac = zeta_D.sum(dim=1)
        return Omega, log_jac

    def log_likelihood(self, X, B, Omega):
        n, p = X.shape
        ImB = self.I.unsqueeze(0) - B

        sign_imb, logdet_imb = torch.linalg.slogdet(ImB)
        sign_om, logdet_om = torch.linalg.slogdet(Omega)

        R = torch.matmul(X.unsqueeze(0), ImB)
        Omega_inv = torch.linalg.inv(Omega)
        quad = torch.einsum("mni,mij,mnj->m", R, Omega_inv, R)

        const = -0.5 * n * p * math.log(2.0 * math.pi)
        ll = n * logdet_imb - 0.5 * n * logdet_om - 0.5 * quad + const

        invalid = (sign_imb <= 0) | (sign_om <= 0) | (~torch.isfinite(ll))
        ll = torch.where(invalid, torch.full_like(ll, -1.0e30), ll)
        return ll

    def kl_terms(self):
        sig_B = self.sigma_from_rho(self.rho_B)
        sig_L = self.sigma_from_rho(self.rho_L)
        sig_D = self.sigma_from_rho(self.rho_D)

        sB2 = self.sigma_B_prior ** 2

        kl_B_mat = 0.5 * (
            sig_B**2 / sB2
            + self.mu_B**2 / sB2
            - 1.0
            - 2.0 * torch.log(sig_B)
            + math.log(sB2)
        )
        kl_B = (kl_B_mat * self.dir_mask).sum()

        kl_L_mat = 0.5 * (
            sig_L**2
            + self.mu_L**2
            - 1.0
            - 2.0 * torch.log(sig_L)
        )
        kl_L = (kl_L_mat * self.l_lower_mask).sum()

        kl_D_vec = 0.5 * (
            sig_D**2
            + self.mu_D**2
            - 1.0
            - 2.0 * torch.log(sig_D)
        )
        kl_D = kl_D_vec.sum()

        kl_Om = kl_L + kl_D
        kl_total = kl_B + kl_Om
        return kl_total, kl_B, kl_Om, kl_L, kl_D

    # --------------------------------------------------------
    # objective
    # --------------------------------------------------------
    def objective(
        self,
        X,
        beta,
        n_mc=8,
        lambda_acyc = 0.5,
        include_log_jac=True,
    ):
        zeta_B, zeta_L, zeta_D = self.sample_zeta(n_mc=n_mc)

        # one gate sample per objective evaluation
        S_soft = self.sample_soft_S()
        C_lower_soft, C_upper_soft = self.sample_C_lower()

        B = self.build_B(zeta_B, S_soft)
        Omega, log_jac = self.build_Omega_and_log_jac(zeta_L, zeta_D, C_lower_soft)

        ll = self.log_likelihood(X, B, Omega)

        if include_log_jac:
            mc_term = beta * ll + log_jac
        else:
            mc_term = beta * ll

        mc_mean = mc_term.mean()

        kl, kl_B, kl_Om, kl_L, kl_D = self.kl_terms()
        h_acyc = torch.trace(torch.matrix_exp(S_soft * S_soft)) - self.d
        elbo = mc_mean - kl
        objective = elbo - lambda_acyc*h_acyc

        return {
            "objective": objective,
            "elbo": elbo,
            "mc_mean": mc_mean,
            "beta_ll_mean": (beta * ll).mean(),
            "ll_mean": ll.mean(),
            "log_jac_mean": log_jac.mean(),
            "kl": kl,
            "kl_B": kl_B,
            "kl_Om": kl_Om,
            "kl_L": kl_L,
            "kl_D": kl_D,
            "S_sample_mean": S_soft.sum(),
            "C_sample_mean": C_upper_soft.sum(),
        }

    # --------------------------------------------------------
    # outputs
    # --------------------------------------------------------
    @torch.no_grad()
    def current_soft_graphs(self):
        S = self.deterministic_S().detach().cpu()
        C = self.deterministic_C_full().detach().cpu()
        return S, C

    @torch.no_grad()
    def threshold_graphs(self, tau_B=0.1, tau_C=0.1):
        S_prob = self.deterministic_S()
        C_up_prob = self.deterministic_C_upper()
        S_bar = max(S_prob.mean(), tau_B)
        C_bar = max(torch.mean(C_up_prob + C_up_prob.T) / 2, tau_C)

        S_hat = (S_prob > S_bar).to(torch.float64)
        C_hat = (C_up_prob > C_bar).to(torch.float64)
        C_hat = C_hat + C_hat.T + torch.eye(self.d, dtype=torch.float64, device=C_hat.device)

        return S_hat.detach().cpu(), C_hat.detach().cpu()

# ============================================================
# 5. Single optimization run
# ============================================================

def fit_continuous_search_gumbel(
    X_np,
    n_steps=3000,
    lr=1e-2,
    n_mc=8,
    sigma_B_prior=2.0,
    tau_gumbel=1.0,
    hard=False,
    init_a_mean=0.0,
    init_u_mean=0.0,
    init_std=0.1,
    tau_B=0.1,
    tau_C=0.1,
    lambda_acyc_init=1.0,    # 初始权重
    lambda_acyc_final=100.0,  # 结束权重
    seed=123,
    device="cpu",
    verbose=True,
    include_log_jac=True,
    grad_clip=10.0,
):
    torch.manual_seed(seed)
    np.random.seed(seed)

    X = torch.tensor(X_np, dtype=torch.float64, device=device)
    n, d_local = X.shape
    beta = 1.0 / math.log(n)

    model = ContinuousADMGSearchGumbel(
        d=d_local,
        sigma_B_prior=sigma_B_prior,
        tau_gumbel=tau_gumbel,
        hard=hard,
        dtype=torch.float64,
        device=device,
    ).to(device=device, dtype=torch.float64)

    model.init_variational(seed=seed)
    model.init_structure_logits(
        a_mean=init_a_mean,
        a_std=init_std,
        u_mean=init_u_mean,
        u_std=init_std,
        seed=seed + 1,
    )

    optimizer = optim.Adam(model.parameters(), lr=lr)

    history = {
        "objective": [],
        "elbo": [],
        "mc_mean": [],
        "beta_ll_mean": [],
        "ll_mean": [],
        "log_jac_mean": [],
        "kl": [],
        "kl_B": [],
        "kl_Om": [],
        "kl_L": [],
        "kl_D": [],
        "S_sample_mean": [],
        "C_sample_mean": [],
    }

    for t in range(n_steps):
        # 指数增长计算当前步骤的权重
        curr_lambda = math.exp(math.log(lambda_acyc_init) + t * (math.log(lambda_acyc_final) - math.log(lambda_acyc_init)) / n_steps)
        optimizer.zero_grad()

        out = model.objective(
            X=X,
            beta=beta,
            n_mc=n_mc,
            lambda_acyc=curr_lambda,
            include_log_jac=include_log_jac,
        )

        loss = -out["objective"]
        loss.backward()

        if grad_clip is not None:
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=grad_clip)

        optimizer.step()

        for k in history:
            history[k].append(float(out[k].detach().cpu()))

        if verbose and (t == 0 or (t + 1) % 200 == 0):
            print(
                f"[step {t+1:5d}] "
                f"obj={history['objective'][-1]:12.4f} "
                f"elbo={history['elbo'][-1]:12.4f} "
                f"ll={history['ll_mean'][-1]:12.4f} "
                f"logJ={history['log_jac_mean'][-1]:9.4f} "
                f"kl={history['kl'][-1]:10.4f} "
                f"Ssum={history['S_sample_mean'][-1]:8.4f} "
                f"Csum={history['C_sample_mean'][-1]:8.4f}"
            )

    S_soft, C_soft = model.current_soft_graphs()
    S_hat, C_hat = model.threshold_graphs(tau_B=tau_B, tau_C=tau_C)

    result = {
        "model": model,
        "history": history,
        "S_soft": S_soft.numpy(),
        "C_soft": C_soft.numpy(),
        "S_hat": S_hat.numpy(),
        "C_hat": C_hat.numpy(),
        "final_objective": history["objective"][-1],
        "final_elbo": history["elbo"][-1],
        "final_ll_mean": history["ll_mean"][-1],
        "final_kl": history["kl"][-1],
    }

    return result

# ============================================================
# 6. Multiple initializations
# ============================================================

def run_multi_init_experiment_gumbel(
    gt,
    n_samples=1000,
    n_steps=3000,
    lr=1e-2,
    n_mc=8,
    sigma_B_prior=2.0,
    tau_gumbel=1.0,
    hard=False,
    tau_B=0.1,
    tau_C=0.1,
    init_configs=None,
    seed_data=42,
    device="cpu",
    include_log_jac=True,
    verbose = True
):
    S_true = gt["S_true"]
    C_true = gt["C_true"]
    B_true = gt["B_true"]
    Omega_true = gt["Omega_true"]

    X_np = simulate_linear_scm_i_to_j(
        n=n_samples,
        B=B_true,
        Omega=Omega_true,
        seed=seed_data,
    )

    if init_configs is None:
        init_configs = [
            {"name": "sparse_sparse", "a_mean": -3.0, "u_mean": -3.0, "std": 0.1, "seed": 101},
            {"name": "sparse_mid",    "a_mean": -3.0, "u_mean":  0.0, "std": 0.1, "seed": 102},
            {"name": "mid_mid",       "a_mean":  0.0, "u_mean":  0.0, "std": 0.1, "seed": 103},
            {"name": "dense_mid",     "a_mean":  3.0, "u_mean":  0.0, "std": 0.1, "seed": 104},
            {"name": "dense_dense",   "a_mean":  3.0, "u_mean":  3.0, "std": 0.1, "seed": 105},
        ]

    all_results = []

    S_true_t = torch.tensor(S_true, dtype=torch.float64)
    C_true_t = torch.tensor(C_true, dtype=torch.float64)

    for cfg in init_configs:
        print("\n" + "=" * 80)
        print(f"INIT: {cfg['name']}")
        print("=" * 80)

        res = fit_continuous_search_gumbel(
            X_np=X_np,
            n_steps=n_steps,
            lr=lr,
            n_mc=n_mc,
            sigma_B_prior=sigma_B_prior,
            tau_gumbel=tau_gumbel,
            hard=hard,
            init_a_mean=cfg["a_mean"],
            init_u_mean=cfg["u_mean"],
            init_std=cfg["std"],
            tau_B=tau_B,
            tau_C=tau_C,
            seed=cfg["seed"],
            device=device,
            verbose=verbose,
            include_log_jac=include_log_jac,
        )

        S_hat_t = torch.tensor(res["S_hat"], dtype=torch.float64)
        C_hat_t = torch.tensor(res["C_hat"], dtype=torch.float64)
        d = S_true_t.shape[0]
        pag_true = admg_to_pag(d,B_mat=S_true,Sigma_mat=C_true)
        try:
          # 尝试生成 PAG，如果 S_hat 包含环，这里会触发 NetworkXError
          pag_hat = admg_to_pag(d, B_mat=res["S_hat"], Sigma_mat=res["C_hat"])
          shd_res = compute_pag_metrics(pag_true, pag_hat)
          shd = shd_res["shd"]

          all_results.append({
            "init_name": cfg["name"],
            "config": cfg,
            "result": res,
            "shd": shd,
          })
          if verbose:
            print("\nFinal metrics:")
            print(
                {
                    "objective": res["final_objective"],
                    "elbo": res["final_elbo"],
                    "ll_mean": res["final_ll_mean"],
                    "kl": res["final_kl"],
                    "l1_B": res["final_l1_B"],
                    "l1_C": res["final_l1_C"],
                }
                )
            print("\nPag True:")
            print(pag_true)
            print("\nPag Hat:")
            print(pag_hat)
            print("\nSHD:")
            print(shd)
        except Exception as e:
          # 捕获错误并跳过该次初始化结果，继续下一次实验
          print(f"[Warning] Skipping init {cfg['name']} due to non-acyclic graph: {e}")
          continue

    all_results = sorted(
        all_results,
        key=lambda z: z["result"]["final_objective"],
        reverse=True,
    )

    if verbose:
        print("\n" + "=" * 80)
        print("SUMMARY OVER INITIALIZATIONS")
        print("=" * 80)

        for k, rr in enumerate(all_results, 1):
            print(
                f"{k:2d}. {rr['init_name']:<15s} "
                f"obj={rr['result']['final_objective']:12.4f} "
                f"elbo={rr['result']['final_elbo']:12.4f} "
                f"ll={rr['result']['final_ll_mean']:12.4f} "
                f"kl={rr['result']['final_kl']:10.4f} "
                f"l1B={rr['result']['final_l1_B']:8.4f} "
                f"l1C={rr['result']['final_l1_C']:8.4f} "
                f"SHD={rr['shd']}"
            )

    return {
        "ground_truth": gt,
        "X": X_np,
        "all_results": all_results,
    }

# ============================================================
# 7. Main, L1
# ============================================================
if __name__ == "__main__":
    n_exp = 10
    d = 5
    all_best_shds = []

    for i in range(n_exp):
        print(f"\n{'#'*30} EXPERIMENT {i+1}/{n_exp} {'#'*30}")
        # 1. Generate random GT
        gt = generate_random_ground_truth_er(
            d=d, p_dir=0.40, p_bidir=0.20, seed=2033 + i
        )

        # 2. Run multi-init search
        exp_results = run_multi_init_experiment_original_param(
            gt=gt, n_samples=1000, n_steps=2000, lr=1e-2,
            alpha_B=0.08, alpha_C=0.08, verbose=False
        )

        if not exp_results['all_results']:
            print(f"[Warning] No valid acyclic graphs were found for Experiment {i+1}. Skipping.")
            continue

        # 3. Find the best result based on the Objective Score (not SHD)
        # all_results is already sorted by final_objective descending in the run function
        best_run = exp_results['all_results'][0]
        all_best_shds.append(best_run['shd'])

        # 4. Print detailed results for this experiment
        print("\n[Ground Truth]")
        print("S_true:\n", gt['S_true'])
        print("C_true:\n", gt['C_true'])

        print("\n[Best Estimate (Selected by Max Objective Score)]")
        print(f"Init Name: {best_run['init_name']}")
        print(f"Final Objective: {best_run['result']['final_objective']:.4f}")
        print("S_hat:\n", best_run['result']['S_hat'])
        print("C_hat:\n", best_run['result']['C_hat'])

        print("\n[PAGs]")
        pag_true = admg_to_pag(d, B_mat=gt['S_true'], Sigma_mat=gt['C_true'])
        pag_hat = admg_to_pag(d, B_mat=best_run['result']['S_hat'], Sigma_mat=best_run['result']['C_hat'])
        print("\nPAG True:")
        print(pag_true)
        print("\nPAG Hat: ")
        print(pag_hat)
        print(f"Current SHD: {best_run['shd']}")

    if all_best_shds:
        avg_shd = sum(all_best_shds) / len(all_best_shds)
        print(f"\n{'='*20} FINAL SUMMARY {'='*20}")
        print(f"Number of Experiments: {len(all_best_shds)}")
        print(f"Average SHD (Best by Score): {avg_shd:.4f}")
    else:
        print(f"\n{'='*20} FINAL SUMMARY {'='*20}")
        print("No valid experiments completed.")

# ============================================================
# 7. Main, gumble
# ============================================================

if __name__ == "__main__":
    n_exp = 5
    d = 5
    all_best_shds = []

    for i in range(n_exp):
        print(f"\n{'#'*30} EXPERIMENT {i+1}/{n_exp} {'#'*30}")
        # 1. Generate random GT
        gt = generate_random_ground_truth_er(
            d=d, p_dir=0.40, p_bidir=0.20, seed=42 + i
        )

        # 2. Run multi-init search
        exp_results = run_multi_init_experiment_gumbel(
            gt=gt, n_samples=1000, n_steps=3000, lr=1e-2,
            verbose=False
        )

        if not exp_results['all_results']:
            print(f"[Warning] No valid acyclic graphs were found for Experiment {i+1}. Skipping.")
            continue

        # 3. Find the best result based on the Objective Score (not SHD)
        # all_results is already sorted by final_objective descending in the run function
        best_run = exp_results['all_results'][0]
        all_best_shds.append(best_run['shd'])

        # 4. Print detailed results for this experiment
        print("\n[Ground Truth]")
        print("S_true:\n", gt['S_true'])
        print("C_true:\n", gt['C_true'])

        print("\n[Best Estimate (Selected by Max Objective Score)]")
        print(f"Init Name: {best_run['init_name']}")
        print(f"Final Objective: {best_run['result']['final_objective']:.4f}")
        print("S_hat:\n", best_run['result']['S_hat'])
        print("C_hat:\n", best_run['result']['C_hat'])

        print("\n[PAGs]")
        pag_true = admg_to_pag(d, B_mat=gt['S_true'], Sigma_mat=gt['C_true'])
        pag_hat = admg_to_pag(d, B_mat=best_run['result']['S_hat'], Sigma_mat=best_run['result']['C_hat'])
        print("\nPAG True:")
        print(pag_true)
        print("\nPAG Hat: ")
        print(pag_hat)
        print(f"Current SHD: {best_run['shd']}")

    if all_best_shds:
        avg_shd = sum(all_best_shds) / len(all_best_shds)
        print(f"\n{'='*20} FINAL SUMMARY {'='*20}")
        print(f"Number of Experiments: {len(all_best_shds)}")
        print(f"Average SHD (Best by Score): {avg_shd:.4f}")
    else:
        print(f"\n{'='*20} FINAL SUMMARY {'='*20}")
        print("No valid experiments completed.")